/*
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import com.c2m.model.MergeByRequestId;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MergeDocumentRefOneOf1
 */
public class MergeDocumentRefOneOf1Test {
    private final MergeDocumentRefOneOf1 model = new MergeDocumentRefOneOf1();

    /**
     * Model tests for MergeDocumentRefOneOf1
     */
    @Test
    public void testMergeDocumentRefOneOf1() {
        // TODO: test MergeDocumentRefOneOf1
    }

    /**
     * Test the property 'mergeByRequestId'
     */
    @Test
    public void mergeByRequestIdTest() {
        // TODO: test mergeByRequestId
    }

}
