/*
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import com.c2m.model.MultiDocJobItem;
import com.c2m.model.PaymentDetails;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubmitMultiDocParams
 */
public class SubmitMultiDocParamsTest {
    private final SubmitMultiDocParams model = new SubmitMultiDocParams();

    /**
     * Model tests for SubmitMultiDocParams
     */
    @Test
    public void testSubmitMultiDocParams() {
        // TODO: test SubmitMultiDocParams
    }

    /**
     * Test the property 'jobTemplate'
     */
    @Test
    public void jobTemplateTest() {
        // TODO: test jobTemplate
    }

    /**
     * Test the property 'multiDocJobs'
     */
    @Test
    public void multiDocJobsTest() {
        // TODO: test multiDocJobs
    }

    /**
     * Test the property 'paymentDetails'
     */
    @Test
    public void paymentDetailsTest() {
        // TODO: test paymentDetails
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
