/*
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import com.c2m.model.ZipRequestIdSource;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ZipDocumentSourceOneOf1
 */
public class ZipDocumentSourceOneOf1Test {
    private final ZipDocumentSourceOneOf1 model = new ZipDocumentSourceOneOf1();

    /**
     * Model tests for ZipDocumentSourceOneOf1
     */
    @Test
    public void testZipDocumentSourceOneOf1() {
        // TODO: test ZipDocumentSourceOneOf1
    }

    /**
     * Test the property 'zipRequestIdSource'
     */
    @Test
    public void zipRequestIdSourceTest() {
        // TODO: test zipRequestIdSource
    }

}
