/**
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UrlSource from './UrlSource';

/**
 * The DocSourceStandardOneOf2 model module.
 * @module c2m_api/model/DocSourceStandardOneOf2
 * @version 2.0.0
 */
class DocSourceStandardOneOf2 {
    /**
     * Constructs a new <code>DocSourceStandardOneOf2</code>.
     * @alias module:c2m_api/model/DocSourceStandardOneOf2
     * @param urlSource {module:c2m_api/model/UrlSource} 
     */
    constructor(urlSource) { 
        
        DocSourceStandardOneOf2.initialize(this, urlSource);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, urlSource) { 
        obj['urlSource'] = urlSource;
    }

    /**
     * Constructs a <code>DocSourceStandardOneOf2</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:c2m_api/model/DocSourceStandardOneOf2} obj Optional instance to populate.
     * @return {module:c2m_api/model/DocSourceStandardOneOf2} The populated <code>DocSourceStandardOneOf2</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DocSourceStandardOneOf2();

            if (data.hasOwnProperty('urlSource')) {
                obj['urlSource'] = UrlSource.constructFromObject(data['urlSource']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DocSourceStandardOneOf2</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DocSourceStandardOneOf2</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DocSourceStandardOneOf2.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `urlSource`
        if (data['urlSource']) { // data not null
          UrlSource.validateJSON(data['urlSource']);
        }

        return true;
    }


}

DocSourceStandardOneOf2.RequiredProperties = ["urlSource"];

/**
 * @member {module:c2m_api/model/UrlSource} urlSource
 */
DocSourceStandardOneOf2.prototype['urlSource'] = undefined;






export default DocSourceStandardOneOf2;

