/**
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Envelope.
* @enum {}
* @readonly
*/
export default class Envelope {
    
        /**
         * value: "standard"
         * @const
         */
        "standard" = "standard";

    
        /**
         * value: "none"
         * @const
         */
        "none" = "none";

    
        /**
         * value: "flat"
         * @const
         */
        "flat" = "flat";

    
        /**
         * value: "double_window"
         * @const
         */
        "double_window" = "double_window";

    

    /**
    * Returns a <code>Envelope</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:c2m_api/model/Envelope} The enum <code>Envelope</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

