/**
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PaperType.
* @enum {}
* @readonly
*/
export default class PaperType {
    
        /**
         * value: "white"
         * @const
         */
        "white" = "white";

    
        /**
         * value: "white_24"
         * @const
         */
        "white_24" = "white_24";

    
        /**
         * value: "ivory"
         * @const
         */
        "ivory" = "ivory";

    
        /**
         * value: "glossy"
         * @const
         */
        "glossy" = "glossy";

    

    /**
    * Returns a <code>PaperType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:c2m_api/model/PaperType} The enum <code>PaperType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

