/**
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RecipientAddressSource from './RecipientAddressSource';

/**
 * The PdfSplitJobItemWithAddress model module.
 * @module c2m_api/model/PdfSplitJobItemWithAddress
 * @version 2.0.0
 */
class PdfSplitJobItemWithAddress {
    /**
     * Constructs a new <code>PdfSplitJobItemWithAddress</code>.
     * @alias module:c2m_api/model/PdfSplitJobItemWithAddress
     * @param startPage {Number} 
     * @param endPage {Number} 
     * @param recipientAddressSource {module:c2m_api/model/RecipientAddressSource} 
     */
    constructor(startPage, endPage, recipientAddressSource) { 
        
        PdfSplitJobItemWithAddress.initialize(this, startPage, endPage, recipientAddressSource);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, startPage, endPage, recipientAddressSource) { 
        obj['startPage'] = startPage;
        obj['endPage'] = endPage;
        obj['recipientAddressSource'] = recipientAddressSource;
    }

    /**
     * Constructs a <code>PdfSplitJobItemWithAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:c2m_api/model/PdfSplitJobItemWithAddress} obj Optional instance to populate.
     * @return {module:c2m_api/model/PdfSplitJobItemWithAddress} The populated <code>PdfSplitJobItemWithAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PdfSplitJobItemWithAddress();

            if (data.hasOwnProperty('startPage')) {
                obj['startPage'] = ApiClient.convertToType(data['startPage'], 'Number');
            }
            if (data.hasOwnProperty('endPage')) {
                obj['endPage'] = ApiClient.convertToType(data['endPage'], 'Number');
            }
            if (data.hasOwnProperty('recipientAddressSource')) {
                obj['recipientAddressSource'] = RecipientAddressSource.constructFromObject(data['recipientAddressSource']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PdfSplitJobItemWithAddress</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PdfSplitJobItemWithAddress</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PdfSplitJobItemWithAddress.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `recipientAddressSource`
        if (data['recipientAddressSource']) { // data not null
          RecipientAddressSource.validateJSON(data['recipientAddressSource']);
        }

        return true;
    }


}

PdfSplitJobItemWithAddress.RequiredProperties = ["startPage", "endPage", "recipientAddressSource"];

/**
 * @member {Number} startPage
 */
PdfSplitJobItemWithAddress.prototype['startPage'] = undefined;

/**
 * @member {Number} endPage
 */
PdfSplitJobItemWithAddress.prototype['endPage'] = undefined;

/**
 * @member {module:c2m_api/model/RecipientAddressSource} recipientAddressSource
 */
PdfSplitJobItemWithAddress.prototype['recipientAddressSource'] = undefined;






export default PdfSplitJobItemWithAddress;

