/**
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PdfSplitJobItemNoAddress model module.
 * @module c2m_api/model/PdfSplitJobItemNoAddress
 * @version 2.0.0
 */
class PdfSplitJobItemNoAddress {
    /**
     * Constructs a new <code>PdfSplitJobItemNoAddress</code>.
     * @alias module:c2m_api/model/PdfSplitJobItemNoAddress
     * @param startPage {Number} 
     * @param endPage {Number} 
     */
    constructor(startPage, endPage) { 
        
        PdfSplitJobItemNoAddress.initialize(this, startPage, endPage);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, startPage, endPage) { 
        obj['startPage'] = startPage;
        obj['endPage'] = endPage;
    }

    /**
     * Constructs a <code>PdfSplitJobItemNoAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:c2m_api/model/PdfSplitJobItemNoAddress} obj Optional instance to populate.
     * @return {module:c2m_api/model/PdfSplitJobItemNoAddress} The populated <code>PdfSplitJobItemNoAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PdfSplitJobItemNoAddress();

            if (data.hasOwnProperty('startPage')) {
                obj['startPage'] = ApiClient.convertToType(data['startPage'], 'Number');
            }
            if (data.hasOwnProperty('endPage')) {
                obj['endPage'] = ApiClient.convertToType(data['endPage'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PdfSplitJobItemNoAddress</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PdfSplitJobItemNoAddress</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PdfSplitJobItemNoAddress.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

PdfSplitJobItemNoAddress.RequiredProperties = ["startPage", "endPage"];

/**
 * @member {Number} startPage
 */
PdfSplitJobItemNoAddress.prototype['startPage'] = undefined;

/**
 * @member {Number} endPage
 */
PdfSplitJobItemNoAddress.prototype['endPage'] = undefined;






export default PdfSplitJobItemNoAddress;

