/**
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import RecipientAddressByList from './RecipientAddressByList';

/**
 * The RecipientAddressSourceOneOf1 model module.
 * @module c2m_api/model/RecipientAddressSourceOneOf1
 * @version 2.0.0
 */
class RecipientAddressSourceOneOf1 {
    /**
     * Constructs a new <code>RecipientAddressSourceOneOf1</code>.
     * @alias module:c2m_api/model/RecipientAddressSourceOneOf1
     * @param recipientAddressByList {module:c2m_api/model/RecipientAddressByList} 
     */
    constructor(recipientAddressByList) { 
        
        RecipientAddressSourceOneOf1.initialize(this, recipientAddressByList);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, recipientAddressByList) { 
        obj['recipientAddressByList'] = recipientAddressByList;
    }

    /**
     * Constructs a <code>RecipientAddressSourceOneOf1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:c2m_api/model/RecipientAddressSourceOneOf1} obj Optional instance to populate.
     * @return {module:c2m_api/model/RecipientAddressSourceOneOf1} The populated <code>RecipientAddressSourceOneOf1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecipientAddressSourceOneOf1();

            if (data.hasOwnProperty('recipientAddressByList')) {
                obj['recipientAddressByList'] = RecipientAddressByList.constructFromObject(data['recipientAddressByList']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RecipientAddressSourceOneOf1</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RecipientAddressSourceOneOf1</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RecipientAddressSourceOneOf1.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `recipientAddressByList`
        if (data['recipientAddressByList']) { // data not null
          RecipientAddressByList.validateJSON(data['recipientAddressByList']);
        }

        return true;
    }


}

RecipientAddressSourceOneOf1.RequiredProperties = ["recipientAddressByList"];

/**
 * @member {module:c2m_api/model/RecipientAddressByList} recipientAddressByList
 */
RecipientAddressSourceOneOf1.prototype['recipientAddressByList'] = undefined;






export default RecipientAddressSourceOneOf1;

