/**
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';

/**
 * The RecipientAddressByList model module.
 * @module c2m_api/model/RecipientAddressByList
 * @version 2.0.0
 */
class RecipientAddressByList {
    /**
     * Constructs a new <code>RecipientAddressByList</code>.
     * @alias module:c2m_api/model/RecipientAddressByList
     * @param addressList {Array.<module:c2m_api/model/Address>} 
     */
    constructor(addressList) { 
        
        RecipientAddressByList.initialize(this, addressList);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, addressList) { 
        obj['addressList'] = addressList;
    }

    /**
     * Constructs a <code>RecipientAddressByList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:c2m_api/model/RecipientAddressByList} obj Optional instance to populate.
     * @return {module:c2m_api/model/RecipientAddressByList} The populated <code>RecipientAddressByList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecipientAddressByList();

            if (data.hasOwnProperty('mappingId')) {
                obj['mappingId'] = ApiClient.convertToType(data['mappingId'], 'Number');
            }
            if (data.hasOwnProperty('addressList')) {
                obj['addressList'] = ApiClient.convertToType(data['addressList'], [Address]);
            }
            if (data.hasOwnProperty('addressListName')) {
                obj['addressListName'] = ApiClient.convertToType(data['addressListName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RecipientAddressByList</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RecipientAddressByList</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RecipientAddressByList.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['addressList']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['addressList'])) {
                throw new Error("Expected the field `addressList` to be an array in the JSON data but got " + data['addressList']);
            }
            // validate the optional field `addressList` (array)
            for (const item of data['addressList']) {
                Address.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['addressListName'] && !(typeof data['addressListName'] === 'string' || data['addressListName'] instanceof String)) {
            throw new Error("Expected the field `addressListName` to be a primitive type in the JSON string but got " + data['addressListName']);
        }

        return true;
    }


}

RecipientAddressByList.RequiredProperties = ["addressList"];

/**
 * @member {Number} mappingId
 */
RecipientAddressByList.prototype['mappingId'] = undefined;

/**
 * @member {Array.<module:c2m_api/model/Address>} addressList
 */
RecipientAddressByList.prototype['addressList'] = undefined;

/**
 * @member {String} addressListName
 */
RecipientAddressByList.prototype['addressListName'] = undefined;






export default RecipientAddressByList;

