/**
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StandardResponse model module.
 * @module c2m_api/model/StandardResponse
 * @version 2.0.0
 */
class StandardResponse {
    /**
     * Constructs a new <code>StandardResponse</code>.
     * @alias module:c2m_api/model/StandardResponse
     * @param status {String} 
     * @param message {String} 
     * @param requestId {Number} 
     */
    constructor(status, message, requestId) { 
        
        StandardResponse.initialize(this, status, message, requestId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status, message, requestId) { 
        obj['status'] = status;
        obj['message'] = message;
        obj['requestId'] = requestId;
    }

    /**
     * Constructs a <code>StandardResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:c2m_api/model/StandardResponse} obj Optional instance to populate.
     * @return {module:c2m_api/model/StandardResponse} The populated <code>StandardResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StandardResponse();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('requestId')) {
                obj['requestId'] = ApiClient.convertToType(data['requestId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StandardResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StandardResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StandardResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }

        return true;
    }


}

StandardResponse.RequiredProperties = ["status", "message", "requestId"];

/**
 * @member {String} status
 */
StandardResponse.prototype['status'] = undefined;

/**
 * @member {String} message
 */
StandardResponse.prototype['message'] = undefined;

/**
 * @member {Number} requestId
 */
StandardResponse.prototype['requestId'] = undefined;






export default StandardResponse;

