/**
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ZipDocumentIdSource model module.
 * @module c2m_api/model/ZipDocumentIdSource
 * @version 2.0.0
 */
class ZipDocumentIdSource {
    /**
     * Constructs a new <code>ZipDocumentIdSource</code>.
     * @alias module:c2m_api/model/ZipDocumentIdSource
     * @param zipDocumentId {Number} 
     * @param filename {String} 
     */
    constructor(zipDocumentId, filename) { 
        
        ZipDocumentIdSource.initialize(this, zipDocumentId, filename);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, zipDocumentId, filename) { 
        obj['zipDocumentId'] = zipDocumentId;
        obj['filename'] = filename;
    }

    /**
     * Constructs a <code>ZipDocumentIdSource</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:c2m_api/model/ZipDocumentIdSource} obj Optional instance to populate.
     * @return {module:c2m_api/model/ZipDocumentIdSource} The populated <code>ZipDocumentIdSource</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ZipDocumentIdSource();

            if (data.hasOwnProperty('zipDocumentId')) {
                obj['zipDocumentId'] = ApiClient.convertToType(data['zipDocumentId'], 'Number');
            }
            if (data.hasOwnProperty('filename')) {
                obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ZipDocumentIdSource</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ZipDocumentIdSource</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ZipDocumentIdSource.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['filename'] && !(typeof data['filename'] === 'string' || data['filename'] instanceof String)) {
            throw new Error("Expected the field `filename` to be a primitive type in the JSON string but got " + data['filename']);
        }

        return true;
    }


}

ZipDocumentIdSource.RequiredProperties = ["zipDocumentId", "filename"];

/**
 * @member {Number} zipDocumentId
 */
ZipDocumentIdSource.prototype['zipDocumentId'] = undefined;

/**
 * @member {String} filename
 */
ZipDocumentIdSource.prototype['filename'] = undefined;






export default ZipDocumentIdSource;

