/**
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ZipRequestIdSource from './ZipRequestIdSource';

/**
 * The ZipDocumentSourceOneOf1 model module.
 * @module c2m_api/model/ZipDocumentSourceOneOf1
 * @version 2.0.0
 */
class ZipDocumentSourceOneOf1 {
    /**
     * Constructs a new <code>ZipDocumentSourceOneOf1</code>.
     * @alias module:c2m_api/model/ZipDocumentSourceOneOf1
     * @param zipRequestIdSource {module:c2m_api/model/ZipRequestIdSource} 
     */
    constructor(zipRequestIdSource) { 
        
        ZipDocumentSourceOneOf1.initialize(this, zipRequestIdSource);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, zipRequestIdSource) { 
        obj['zipRequestIdSource'] = zipRequestIdSource;
    }

    /**
     * Constructs a <code>ZipDocumentSourceOneOf1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:c2m_api/model/ZipDocumentSourceOneOf1} obj Optional instance to populate.
     * @return {module:c2m_api/model/ZipDocumentSourceOneOf1} The populated <code>ZipDocumentSourceOneOf1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ZipDocumentSourceOneOf1();

            if (data.hasOwnProperty('zipRequestIdSource')) {
                obj['zipRequestIdSource'] = ZipRequestIdSource.constructFromObject(data['zipRequestIdSource']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ZipDocumentSourceOneOf1</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ZipDocumentSourceOneOf1</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ZipDocumentSourceOneOf1.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `zipRequestIdSource`
        if (data['zipRequestIdSource']) { // data not null
          ZipRequestIdSource.validateJSON(data['zipRequestIdSource']);
        }

        return true;
    }


}

ZipDocumentSourceOneOf1.RequiredProperties = ["zipRequestIdSource"];

/**
 * @member {module:c2m_api/model/ZipRequestIdSource} zipRequestIdSource
 */
ZipDocumentSourceOneOf1.prototype['zipRequestIdSource'] = undefined;






export default ZipDocumentSourceOneOf1;

