/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.c2m.api.models.DocSourceStandardOneOf
import com.c2m.api.models.DocumentIdSource

class DocSourceStandardOneOfTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DocSourceStandardOneOf
        //val modelInstance = DocSourceStandardOneOf()

        // to test the property `documentIdSource`
        should("test documentIdSource") {
            // uncomment below to test the property
            //modelInstance.documentIdSource shouldBe ("TODO")
        }

    }
}
