/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import com.c2m.api.models.MergeDocumentRef
import com.c2m.api.models.MergeByRequestId

class MergeDocumentRefTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MergeDocumentRef
        //val modelInstance = MergeDocumentRef()

        // to test the property `requestId`
        should("test requestId") {
            // uncomment below to test the property
            //modelInstance.requestId shouldBe ("TODO")
        }

        // to test the property `filename`
        should("test filename") {
            // uncomment below to test the property
            //modelInstance.filename shouldBe ("TODO")
        }

    }
}
