//
// DocSourceZipFileRefOneOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DocSourceZipFileRefOneOf: Codable, JSONEncodable, Hashable {

    public var zipDocumentIdOnly: ZipDocumentIdOnly

    public init(zipDocumentIdOnly: ZipDocumentIdOnly) {
        self.zipDocumentIdOnly = zipDocumentIdOnly
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case zipDocumentIdOnly
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(zipDocumentIdOnly, forKey: .zipDocumentIdOnly)
    }
}

