//
// Envelope.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum Envelope: String, Codable, CaseIterable {
    case standard = "standard"
    case _none = "none"
    case flat = "flat"
    case doubleWindow = "double_window"
}
