//
// ErrorType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ErrorType: String, Codable, CaseIterable {
    case validationError = "ValidationError"
    case authenticationError = "AuthenticationError"
    case authorizationError = "AuthorizationError"
    case resourceNotFoundError = "ResourceNotFoundError"
    case serverError = "ServerError"
}
