//
// PaymentType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PaymentType: String, Codable, CaseIterable {
    case creditcard = "creditCard"
    case invoice = "invoice"
    case ach = "ach"
    case usercredit = "userCredit"
}
