//
// PrioritySpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum PrioritySpec: String, Codable, CaseIterable {
    case standard = "standard"
    case rush = "rush"
    case overnight = "overnight"
}
