/*
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import java.util.Objects;
import com.c2m.model.DocSourceStandardOneOf;
import com.c2m.model.DocSourceStandardOneOf1;
import com.c2m.model.DocSourceStandardOneOf2;
import com.c2m.model.DocumentIdSource;
import com.c2m.model.RequestIdSource;
import com.c2m.model.UrlSource;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import com.c2m.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-19T01:02:08.960701731Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class DocSourceStandard extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(DocSourceStandard.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!DocSourceStandard.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'DocSourceStandard' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<DocSourceStandardOneOf> adapterDocSourceStandardOneOf = gson.getDelegateAdapter(this, TypeToken.get(DocSourceStandardOneOf.class));
            final TypeAdapter<DocSourceStandardOneOf1> adapterDocSourceStandardOneOf1 = gson.getDelegateAdapter(this, TypeToken.get(DocSourceStandardOneOf1.class));
            final TypeAdapter<DocSourceStandardOneOf2> adapterDocSourceStandardOneOf2 = gson.getDelegateAdapter(this, TypeToken.get(DocSourceStandardOneOf2.class));

            return (TypeAdapter<T>) new TypeAdapter<DocSourceStandard>() {
                @Override
                public void write(JsonWriter out, DocSourceStandard value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `DocSourceStandardOneOf`
                    if (value.getActualInstance() instanceof DocSourceStandardOneOf) {
                        JsonElement element = adapterDocSourceStandardOneOf.toJsonTree((DocSourceStandardOneOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `DocSourceStandardOneOf1`
                    if (value.getActualInstance() instanceof DocSourceStandardOneOf1) {
                        JsonElement element = adapterDocSourceStandardOneOf1.toJsonTree((DocSourceStandardOneOf1)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `DocSourceStandardOneOf2`
                    if (value.getActualInstance() instanceof DocSourceStandardOneOf2) {
                        JsonElement element = adapterDocSourceStandardOneOf2.toJsonTree((DocSourceStandardOneOf2)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: DocSourceStandardOneOf, DocSourceStandardOneOf1, DocSourceStandardOneOf2");
                }

                @Override
                public DocSourceStandard read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize DocSourceStandardOneOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        DocSourceStandardOneOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterDocSourceStandardOneOf;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'DocSourceStandardOneOf'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for DocSourceStandardOneOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'DocSourceStandardOneOf'", e);
                    }
                    // deserialize DocSourceStandardOneOf1
                    try {
                        // validate the JSON object to see if any exception is thrown
                        DocSourceStandardOneOf1.validateJsonElement(jsonElement);
                        actualAdapter = adapterDocSourceStandardOneOf1;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'DocSourceStandardOneOf1'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for DocSourceStandardOneOf1 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'DocSourceStandardOneOf1'", e);
                    }
                    // deserialize DocSourceStandardOneOf2
                    try {
                        // validate the JSON object to see if any exception is thrown
                        DocSourceStandardOneOf2.validateJsonElement(jsonElement);
                        actualAdapter = adapterDocSourceStandardOneOf2;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'DocSourceStandardOneOf2'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for DocSourceStandardOneOf2 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'DocSourceStandardOneOf2'", e);
                    }

                    if (match == 1) {
                        DocSourceStandard ret = new DocSourceStandard();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for DocSourceStandard: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public DocSourceStandard() {
        super("oneOf", Boolean.FALSE);
    }

    public DocSourceStandard(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("DocSourceStandardOneOf", DocSourceStandardOneOf.class);
        schemas.put("DocSourceStandardOneOf1", DocSourceStandardOneOf1.class);
        schemas.put("DocSourceStandardOneOf2", DocSourceStandardOneOf2.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return DocSourceStandard.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * DocSourceStandardOneOf, DocSourceStandardOneOf1, DocSourceStandardOneOf2
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof DocSourceStandardOneOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof DocSourceStandardOneOf1) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof DocSourceStandardOneOf2) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be DocSourceStandardOneOf, DocSourceStandardOneOf1, DocSourceStandardOneOf2");
    }

    /**
     * Get the actual instance, which can be the following:
     * DocSourceStandardOneOf, DocSourceStandardOneOf1, DocSourceStandardOneOf2
     *
     * @return The actual instance (DocSourceStandardOneOf, DocSourceStandardOneOf1, DocSourceStandardOneOf2)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `DocSourceStandardOneOf`. If the actual instance is not `DocSourceStandardOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DocSourceStandardOneOf`
     * @throws ClassCastException if the instance is not `DocSourceStandardOneOf`
     */
    public DocSourceStandardOneOf getDocSourceStandardOneOf() throws ClassCastException {
        return (DocSourceStandardOneOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `DocSourceStandardOneOf1`. If the actual instance is not `DocSourceStandardOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DocSourceStandardOneOf1`
     * @throws ClassCastException if the instance is not `DocSourceStandardOneOf1`
     */
    public DocSourceStandardOneOf1 getDocSourceStandardOneOf1() throws ClassCastException {
        return (DocSourceStandardOneOf1)super.getActualInstance();
    }

    /**
     * Get the actual instance of `DocSourceStandardOneOf2`. If the actual instance is not `DocSourceStandardOneOf2`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `DocSourceStandardOneOf2`
     * @throws ClassCastException if the instance is not `DocSourceStandardOneOf2`
     */
    public DocSourceStandardOneOf2 getDocSourceStandardOneOf2() throws ClassCastException {
        return (DocSourceStandardOneOf2)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to DocSourceStandard
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with DocSourceStandardOneOf
        try {
            DocSourceStandardOneOf.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for DocSourceStandardOneOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with DocSourceStandardOneOf1
        try {
            DocSourceStandardOneOf1.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for DocSourceStandardOneOf1 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with DocSourceStandardOneOf2
        try {
            DocSourceStandardOneOf2.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for DocSourceStandardOneOf2 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for DocSourceStandard with oneOf schemas: DocSourceStandardOneOf, DocSourceStandardOneOf1, DocSourceStandardOneOf2. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of DocSourceStandard given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of DocSourceStandard
     * @throws IOException if the JSON string is invalid with respect to DocSourceStandard
     */
    public static DocSourceStandard fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, DocSourceStandard.class);
    }

    /**
     * Convert an instance of DocSourceStandard to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

