/*
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import java.util.Objects;
import com.c2m.model.ZipDocumentIdSource;
import com.c2m.model.ZipRequestIdSource;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import com.c2m.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-13T04:38:16.937160206Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class DocSourceZipFile extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(DocSourceZipFile.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!DocSourceZipFile.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'DocSourceZipFile' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<ZipDocumentIdSource> adapterZipDocumentIdSource = gson.getDelegateAdapter(this, TypeToken.get(ZipDocumentIdSource.class));
            final TypeAdapter<ZipRequestIdSource> adapterZipRequestIdSource = gson.getDelegateAdapter(this, TypeToken.get(ZipRequestIdSource.class));

            return (TypeAdapter<T>) new TypeAdapter<DocSourceZipFile>() {
                @Override
                public void write(JsonWriter out, DocSourceZipFile value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `ZipDocumentIdSource`
                    if (value.getActualInstance() instanceof ZipDocumentIdSource) {
                        JsonElement element = adapterZipDocumentIdSource.toJsonTree((ZipDocumentIdSource)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `ZipRequestIdSource`
                    if (value.getActualInstance() instanceof ZipRequestIdSource) {
                        JsonElement element = adapterZipRequestIdSource.toJsonTree((ZipRequestIdSource)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: ZipDocumentIdSource, ZipRequestIdSource");
                }

                @Override
                public DocSourceZipFile read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize ZipDocumentIdSource
                    try {
                        // validate the JSON object to see if any exception is thrown
                        ZipDocumentIdSource.validateJsonElement(jsonElement);
                        actualAdapter = adapterZipDocumentIdSource;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'ZipDocumentIdSource'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for ZipDocumentIdSource failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'ZipDocumentIdSource'", e);
                    }
                    // deserialize ZipRequestIdSource
                    try {
                        // validate the JSON object to see if any exception is thrown
                        ZipRequestIdSource.validateJsonElement(jsonElement);
                        actualAdapter = adapterZipRequestIdSource;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'ZipRequestIdSource'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for ZipRequestIdSource failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'ZipRequestIdSource'", e);
                    }

                    if (match == 1) {
                        DocSourceZipFile ret = new DocSourceZipFile();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for DocSourceZipFile: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public DocSourceZipFile() {
        super("oneOf", Boolean.FALSE);
    }

    public DocSourceZipFile(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("ZipDocumentIdSource", ZipDocumentIdSource.class);
        schemas.put("ZipRequestIdSource", ZipRequestIdSource.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return DocSourceZipFile.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * ZipDocumentIdSource, ZipRequestIdSource
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof ZipDocumentIdSource) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof ZipRequestIdSource) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be ZipDocumentIdSource, ZipRequestIdSource");
    }

    /**
     * Get the actual instance, which can be the following:
     * ZipDocumentIdSource, ZipRequestIdSource
     *
     * @return The actual instance (ZipDocumentIdSource, ZipRequestIdSource)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `ZipDocumentIdSource`. If the actual instance is not `ZipDocumentIdSource`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ZipDocumentIdSource`
     * @throws ClassCastException if the instance is not `ZipDocumentIdSource`
     */
    public ZipDocumentIdSource getZipDocumentIdSource() throws ClassCastException {
        return (ZipDocumentIdSource)super.getActualInstance();
    }

    /**
     * Get the actual instance of `ZipRequestIdSource`. If the actual instance is not `ZipRequestIdSource`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `ZipRequestIdSource`
     * @throws ClassCastException if the instance is not `ZipRequestIdSource`
     */
    public ZipRequestIdSource getZipRequestIdSource() throws ClassCastException {
        return (ZipRequestIdSource)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to DocSourceZipFile
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with ZipDocumentIdSource
        try {
            ZipDocumentIdSource.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for ZipDocumentIdSource failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with ZipRequestIdSource
        try {
            ZipRequestIdSource.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for ZipRequestIdSource failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for DocSourceZipFile with oneOf schemas: ZipDocumentIdSource, ZipRequestIdSource. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of DocSourceZipFile given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of DocSourceZipFile
     * @throws IOException if the JSON string is invalid with respect to DocSourceZipFile
     */
    public static DocSourceZipFile fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, DocSourceZipFile.class);
    }

    /**
     * Convert an instance of DocSourceZipFile to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

