/*
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import java.util.Objects;
import com.c2m.model.DocumentSourceIdentifier;
import com.c2m.model.PaymentDetails;
import com.c2m.model.RecipientAddressSource;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.c2m.JSON;

/**
 * MergeMultiDocParams
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-10-26T03:49:36.434628138Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class MergeMultiDocParams {
  public static final String SERIALIZED_NAME_DOCUMENTS_TO_MERGE = "documentsToMerge";
  @SerializedName(SERIALIZED_NAME_DOCUMENTS_TO_MERGE)
  @javax.annotation.Nonnull
  private List<DocumentSourceIdentifier> documentsToMerge = new ArrayList<>();

  public static final String SERIALIZED_NAME_RECIPIENT_ADDRESS_SOURCE = "recipientAddressSource";
  @SerializedName(SERIALIZED_NAME_RECIPIENT_ADDRESS_SOURCE)
  @javax.annotation.Nonnull
  private RecipientAddressSource recipientAddressSource;

  public static final String SERIALIZED_NAME_PAYMENT_DETAILS = "paymentDetails";
  @SerializedName(SERIALIZED_NAME_PAYMENT_DETAILS)
  @javax.annotation.Nonnull
  private PaymentDetails paymentDetails;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public MergeMultiDocParams() {
  }

  public MergeMultiDocParams documentsToMerge(@javax.annotation.Nonnull List<DocumentSourceIdentifier> documentsToMerge) {
    this.documentsToMerge = documentsToMerge;
    return this;
  }

  public MergeMultiDocParams addDocumentsToMergeItem(DocumentSourceIdentifier documentsToMergeItem) {
    if (this.documentsToMerge == null) {
      this.documentsToMerge = new ArrayList<>();
    }
    this.documentsToMerge.add(documentsToMergeItem);
    return this;
  }

  /**
   * Get documentsToMerge
   * @return documentsToMerge
   */
  @javax.annotation.Nonnull
  public List<DocumentSourceIdentifier> getDocumentsToMerge() {
    return documentsToMerge;
  }

  public void setDocumentsToMerge(@javax.annotation.Nonnull List<DocumentSourceIdentifier> documentsToMerge) {
    this.documentsToMerge = documentsToMerge;
  }


  public MergeMultiDocParams recipientAddressSource(@javax.annotation.Nonnull RecipientAddressSource recipientAddressSource) {
    this.recipientAddressSource = recipientAddressSource;
    return this;
  }

  /**
   * Get recipientAddressSource
   * @return recipientAddressSource
   */
  @javax.annotation.Nonnull
  public RecipientAddressSource getRecipientAddressSource() {
    return recipientAddressSource;
  }

  public void setRecipientAddressSource(@javax.annotation.Nonnull RecipientAddressSource recipientAddressSource) {
    this.recipientAddressSource = recipientAddressSource;
  }


  public MergeMultiDocParams paymentDetails(@javax.annotation.Nonnull PaymentDetails paymentDetails) {
    this.paymentDetails = paymentDetails;
    return this;
  }

  /**
   * Get paymentDetails
   * @return paymentDetails
   */
  @javax.annotation.Nonnull
  public PaymentDetails getPaymentDetails() {
    return paymentDetails;
  }

  public void setPaymentDetails(@javax.annotation.Nonnull PaymentDetails paymentDetails) {
    this.paymentDetails = paymentDetails;
  }


  public MergeMultiDocParams tags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
    return this;
  }

  public MergeMultiDocParams addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  public List<String> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MergeMultiDocParams mergeMultiDocParams = (MergeMultiDocParams) o;
    return Objects.equals(this.documentsToMerge, mergeMultiDocParams.documentsToMerge) &&
        Objects.equals(this.recipientAddressSource, mergeMultiDocParams.recipientAddressSource) &&
        Objects.equals(this.paymentDetails, mergeMultiDocParams.paymentDetails) &&
        Objects.equals(this.tags, mergeMultiDocParams.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentsToMerge, recipientAddressSource, paymentDetails, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MergeMultiDocParams {\n");
    sb.append("    documentsToMerge: ").append(toIndentedString(documentsToMerge)).append("\n");
    sb.append("    recipientAddressSource: ").append(toIndentedString(recipientAddressSource)).append("\n");
    sb.append("    paymentDetails: ").append(toIndentedString(paymentDetails)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("documentsToMerge", "recipientAddressSource", "paymentDetails", "tags"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("documentsToMerge", "recipientAddressSource", "paymentDetails"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MergeMultiDocParams
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MergeMultiDocParams.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MergeMultiDocParams is not found in the empty JSON string", MergeMultiDocParams.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MergeMultiDocParams.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MergeMultiDocParams` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MergeMultiDocParams.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("documentsToMerge").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `documentsToMerge` to be an array in the JSON string but got `%s`", jsonObj.get("documentsToMerge").toString()));
      }

      JsonArray jsonArraydocumentsToMerge = jsonObj.getAsJsonArray("documentsToMerge");
      // validate the required field `documentsToMerge` (array)
      for (int i = 0; i < jsonArraydocumentsToMerge.size(); i++) {
        DocumentSourceIdentifier.validateJsonElement(jsonArraydocumentsToMerge.get(i));
      };
      // validate the required field `recipientAddressSource`
      RecipientAddressSource.validateJsonElement(jsonObj.get("recipientAddressSource"));
      // validate the required field `paymentDetails`
      PaymentDetails.validateJsonElement(jsonObj.get("paymentDetails"));
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull() && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MergeMultiDocParams.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MergeMultiDocParams' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MergeMultiDocParams> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MergeMultiDocParams.class));

       return (TypeAdapter<T>) new TypeAdapter<MergeMultiDocParams>() {
           @Override
           public void write(JsonWriter out, MergeMultiDocParams value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MergeMultiDocParams read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MergeMultiDocParams given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MergeMultiDocParams
   * @throws IOException if the JSON string is invalid with respect to MergeMultiDocParams
   */
  public static MergeMultiDocParams fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MergeMultiDocParams.class);
  }

  /**
   * Convert an instance of MergeMultiDocParams to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

