/*
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import java.util.Objects;
import com.c2m.model.MergeByDocumentId;
import com.c2m.model.MergeByRequestId;
import com.c2m.model.MergeDocumentRefOneOf;
import com.c2m.model.MergeDocumentRefOneOf1;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import com.c2m.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-15T07:21:03.354774142Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class MergeDocumentRef extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(MergeDocumentRef.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!MergeDocumentRef.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'MergeDocumentRef' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<MergeDocumentRefOneOf> adapterMergeDocumentRefOneOf = gson.getDelegateAdapter(this, TypeToken.get(MergeDocumentRefOneOf.class));
            final TypeAdapter<MergeDocumentRefOneOf1> adapterMergeDocumentRefOneOf1 = gson.getDelegateAdapter(this, TypeToken.get(MergeDocumentRefOneOf1.class));

            return (TypeAdapter<T>) new TypeAdapter<MergeDocumentRef>() {
                @Override
                public void write(JsonWriter out, MergeDocumentRef value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `MergeDocumentRefOneOf`
                    if (value.getActualInstance() instanceof MergeDocumentRefOneOf) {
                        JsonElement element = adapterMergeDocumentRefOneOf.toJsonTree((MergeDocumentRefOneOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `MergeDocumentRefOneOf1`
                    if (value.getActualInstance() instanceof MergeDocumentRefOneOf1) {
                        JsonElement element = adapterMergeDocumentRefOneOf1.toJsonTree((MergeDocumentRefOneOf1)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: MergeDocumentRefOneOf, MergeDocumentRefOneOf1");
                }

                @Override
                public MergeDocumentRef read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize MergeDocumentRefOneOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        MergeDocumentRefOneOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterMergeDocumentRefOneOf;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'MergeDocumentRefOneOf'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for MergeDocumentRefOneOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'MergeDocumentRefOneOf'", e);
                    }
                    // deserialize MergeDocumentRefOneOf1
                    try {
                        // validate the JSON object to see if any exception is thrown
                        MergeDocumentRefOneOf1.validateJsonElement(jsonElement);
                        actualAdapter = adapterMergeDocumentRefOneOf1;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'MergeDocumentRefOneOf1'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for MergeDocumentRefOneOf1 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'MergeDocumentRefOneOf1'", e);
                    }

                    if (match == 1) {
                        MergeDocumentRef ret = new MergeDocumentRef();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for MergeDocumentRef: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public MergeDocumentRef() {
        super("oneOf", Boolean.FALSE);
    }

    public MergeDocumentRef(Object o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("MergeDocumentRefOneOf", MergeDocumentRefOneOf.class);
        schemas.put("MergeDocumentRefOneOf1", MergeDocumentRefOneOf1.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return MergeDocumentRef.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * MergeDocumentRefOneOf, MergeDocumentRefOneOf1
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof MergeDocumentRefOneOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof MergeDocumentRefOneOf1) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be MergeDocumentRefOneOf, MergeDocumentRefOneOf1");
    }

    /**
     * Get the actual instance, which can be the following:
     * MergeDocumentRefOneOf, MergeDocumentRefOneOf1
     *
     * @return The actual instance (MergeDocumentRefOneOf, MergeDocumentRefOneOf1)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `MergeDocumentRefOneOf`. If the actual instance is not `MergeDocumentRefOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `MergeDocumentRefOneOf`
     * @throws ClassCastException if the instance is not `MergeDocumentRefOneOf`
     */
    public MergeDocumentRefOneOf getMergeDocumentRefOneOf() throws ClassCastException {
        return (MergeDocumentRefOneOf)super.getActualInstance();
    }

    /**
     * Get the actual instance of `MergeDocumentRefOneOf1`. If the actual instance is not `MergeDocumentRefOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `MergeDocumentRefOneOf1`
     * @throws ClassCastException if the instance is not `MergeDocumentRefOneOf1`
     */
    public MergeDocumentRefOneOf1 getMergeDocumentRefOneOf1() throws ClassCastException {
        return (MergeDocumentRefOneOf1)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to MergeDocumentRef
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with MergeDocumentRefOneOf
        try {
            MergeDocumentRefOneOf.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for MergeDocumentRefOneOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with MergeDocumentRefOneOf1
        try {
            MergeDocumentRefOneOf1.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for MergeDocumentRefOneOf1 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for MergeDocumentRef with oneOf schemas: MergeDocumentRefOneOf, MergeDocumentRefOneOf1. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of MergeDocumentRef given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of MergeDocumentRef
     * @throws IOException if the JSON string is invalid with respect to MergeDocumentRef
     */
    public static MergeDocumentRef fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, MergeDocumentRef.class);
    }

    /**
     * Convert an instance of MergeDocumentRef to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

