/*
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import java.util.Objects;
import com.c2m.model.DocSourceAll;
import com.c2m.model.RecipientAddressSource;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.c2m.JSON;

/**
 * MultiDocJobItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-19T01:06:39.591945299Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class MultiDocJobItem {
  public static final String SERIALIZED_NAME_JOB_TEMPLATE = "jobTemplate";
  @SerializedName(SERIALIZED_NAME_JOB_TEMPLATE)
  @javax.annotation.Nullable
  private String jobTemplate;

  public static final String SERIALIZED_NAME_DOC_SOURCE_ALL = "docSourceAll";
  @SerializedName(SERIALIZED_NAME_DOC_SOURCE_ALL)
  @javax.annotation.Nonnull
  private DocSourceAll docSourceAll;

  public static final String SERIALIZED_NAME_RECIPIENT_ADDRESS_SOURCE = "recipientAddressSource";
  @SerializedName(SERIALIZED_NAME_RECIPIENT_ADDRESS_SOURCE)
  @javax.annotation.Nonnull
  private RecipientAddressSource recipientAddressSource;

  public MultiDocJobItem() {
  }

  public MultiDocJobItem jobTemplate(@javax.annotation.Nullable String jobTemplate) {
    this.jobTemplate = jobTemplate;
    return this;
  }

  /**
   * Get jobTemplate
   * @return jobTemplate
   */
  @javax.annotation.Nullable
  public String getJobTemplate() {
    return jobTemplate;
  }

  public void setJobTemplate(@javax.annotation.Nullable String jobTemplate) {
    this.jobTemplate = jobTemplate;
  }


  public MultiDocJobItem docSourceAll(@javax.annotation.Nonnull DocSourceAll docSourceAll) {
    this.docSourceAll = docSourceAll;
    return this;
  }

  /**
   * Get docSourceAll
   * @return docSourceAll
   */
  @javax.annotation.Nonnull
  public DocSourceAll getDocSourceAll() {
    return docSourceAll;
  }

  public void setDocSourceAll(@javax.annotation.Nonnull DocSourceAll docSourceAll) {
    this.docSourceAll = docSourceAll;
  }


  public MultiDocJobItem recipientAddressSource(@javax.annotation.Nonnull RecipientAddressSource recipientAddressSource) {
    this.recipientAddressSource = recipientAddressSource;
    return this;
  }

  /**
   * Get recipientAddressSource
   * @return recipientAddressSource
   */
  @javax.annotation.Nonnull
  public RecipientAddressSource getRecipientAddressSource() {
    return recipientAddressSource;
  }

  public void setRecipientAddressSource(@javax.annotation.Nonnull RecipientAddressSource recipientAddressSource) {
    this.recipientAddressSource = recipientAddressSource;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MultiDocJobItem multiDocJobItem = (MultiDocJobItem) o;
    return Objects.equals(this.jobTemplate, multiDocJobItem.jobTemplate) &&
        Objects.equals(this.docSourceAll, multiDocJobItem.docSourceAll) &&
        Objects.equals(this.recipientAddressSource, multiDocJobItem.recipientAddressSource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobTemplate, docSourceAll, recipientAddressSource);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultiDocJobItem {\n");
    sb.append("    jobTemplate: ").append(toIndentedString(jobTemplate)).append("\n");
    sb.append("    docSourceAll: ").append(toIndentedString(docSourceAll)).append("\n");
    sb.append("    recipientAddressSource: ").append(toIndentedString(recipientAddressSource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("jobTemplate", "docSourceAll", "recipientAddressSource"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("docSourceAll", "recipientAddressSource"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to MultiDocJobItem
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!MultiDocJobItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MultiDocJobItem is not found in the empty JSON string", MultiDocJobItem.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!MultiDocJobItem.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MultiDocJobItem` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : MultiDocJobItem.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("jobTemplate") != null && !jsonObj.get("jobTemplate").isJsonNull()) && !jsonObj.get("jobTemplate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `jobTemplate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("jobTemplate").toString()));
      }
      // validate the required field `docSourceAll`
      DocSourceAll.validateJsonElement(jsonObj.get("docSourceAll"));
      // validate the required field `recipientAddressSource`
      RecipientAddressSource.validateJsonElement(jsonObj.get("recipientAddressSource"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MultiDocJobItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MultiDocJobItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MultiDocJobItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MultiDocJobItem.class));

       return (TypeAdapter<T>) new TypeAdapter<MultiDocJobItem>() {
           @Override
           public void write(JsonWriter out, MultiDocJobItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MultiDocJobItem read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of MultiDocJobItem given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of MultiDocJobItem
   * @throws IOException if the JSON string is invalid with respect to MultiDocJobItem
   */
  public static MultiDocJobItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MultiDocJobItem.class);
  }

  /**
   * Convert an instance of MultiDocJobItem to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

