/*
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import java.util.Objects;
import com.c2m.model.RecipientAddressSource;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.c2m.JSON;

/**
 * PdfSplitJobItemWithAddress
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-19T00:15:44.475409135Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class PdfSplitJobItemWithAddress {
  public static final String SERIALIZED_NAME_START_PAGE = "startPage";
  @SerializedName(SERIALIZED_NAME_START_PAGE)
  @javax.annotation.Nonnull
  private Integer startPage;

  public static final String SERIALIZED_NAME_END_PAGE = "endPage";
  @SerializedName(SERIALIZED_NAME_END_PAGE)
  @javax.annotation.Nonnull
  private Integer endPage;

  public static final String SERIALIZED_NAME_RECIPIENT_ADDRESS_SOURCE = "recipientAddressSource";
  @SerializedName(SERIALIZED_NAME_RECIPIENT_ADDRESS_SOURCE)
  @javax.annotation.Nonnull
  private RecipientAddressSource recipientAddressSource;

  public PdfSplitJobItemWithAddress() {
  }

  public PdfSplitJobItemWithAddress startPage(@javax.annotation.Nonnull Integer startPage) {
    this.startPage = startPage;
    return this;
  }

  /**
   * Get startPage
   * @return startPage
   */
  @javax.annotation.Nonnull
  public Integer getStartPage() {
    return startPage;
  }

  public void setStartPage(@javax.annotation.Nonnull Integer startPage) {
    this.startPage = startPage;
  }


  public PdfSplitJobItemWithAddress endPage(@javax.annotation.Nonnull Integer endPage) {
    this.endPage = endPage;
    return this;
  }

  /**
   * Get endPage
   * @return endPage
   */
  @javax.annotation.Nonnull
  public Integer getEndPage() {
    return endPage;
  }

  public void setEndPage(@javax.annotation.Nonnull Integer endPage) {
    this.endPage = endPage;
  }


  public PdfSplitJobItemWithAddress recipientAddressSource(@javax.annotation.Nonnull RecipientAddressSource recipientAddressSource) {
    this.recipientAddressSource = recipientAddressSource;
    return this;
  }

  /**
   * Get recipientAddressSource
   * @return recipientAddressSource
   */
  @javax.annotation.Nonnull
  public RecipientAddressSource getRecipientAddressSource() {
    return recipientAddressSource;
  }

  public void setRecipientAddressSource(@javax.annotation.Nonnull RecipientAddressSource recipientAddressSource) {
    this.recipientAddressSource = recipientAddressSource;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PdfSplitJobItemWithAddress pdfSplitJobItemWithAddress = (PdfSplitJobItemWithAddress) o;
    return Objects.equals(this.startPage, pdfSplitJobItemWithAddress.startPage) &&
        Objects.equals(this.endPage, pdfSplitJobItemWithAddress.endPage) &&
        Objects.equals(this.recipientAddressSource, pdfSplitJobItemWithAddress.recipientAddressSource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startPage, endPage, recipientAddressSource);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PdfSplitJobItemWithAddress {\n");
    sb.append("    startPage: ").append(toIndentedString(startPage)).append("\n");
    sb.append("    endPage: ").append(toIndentedString(endPage)).append("\n");
    sb.append("    recipientAddressSource: ").append(toIndentedString(recipientAddressSource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("startPage", "endPage", "recipientAddressSource"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("startPage", "endPage", "recipientAddressSource"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PdfSplitJobItemWithAddress
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PdfSplitJobItemWithAddress.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PdfSplitJobItemWithAddress is not found in the empty JSON string", PdfSplitJobItemWithAddress.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PdfSplitJobItemWithAddress.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PdfSplitJobItemWithAddress` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : PdfSplitJobItemWithAddress.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `recipientAddressSource`
      RecipientAddressSource.validateJsonElement(jsonObj.get("recipientAddressSource"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PdfSplitJobItemWithAddress.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PdfSplitJobItemWithAddress' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PdfSplitJobItemWithAddress> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PdfSplitJobItemWithAddress.class));

       return (TypeAdapter<T>) new TypeAdapter<PdfSplitJobItemWithAddress>() {
           @Override
           public void write(JsonWriter out, PdfSplitJobItemWithAddress value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PdfSplitJobItemWithAddress read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PdfSplitJobItemWithAddress given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PdfSplitJobItemWithAddress
   * @throws IOException if the JSON string is invalid with respect to PdfSplitJobItemWithAddress
   */
  public static PdfSplitJobItemWithAddress fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PdfSplitJobItemWithAddress.class);
  }

  /**
   * Convert an instance of PdfSplitJobItemWithAddress to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

