/*
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.JsonElement;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets printOption
 */
@JsonAdapter(PrintOption.Adapter.class)
public enum PrintOption {
  
  DOUBLE_SIDED("double_sided"),
  
  SINGLE_SIDED("single_sided");

  private String value;

  PrintOption(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PrintOption fromValue(String value) {
    for (PrintOption b : PrintOption.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PrintOption> {
    @Override
    public void write(final JsonWriter jsonWriter, final PrintOption enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PrintOption read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PrintOption.fromValue(value);
    }
  }

  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
    String value = jsonElement.getAsString();
    PrintOption.fromValue(value);
  }
}

