/*
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.c2m.JSON;

/**
 * RecipientAddressSourceOneOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-18T14:18:40.161107459Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class RecipientAddressSourceOneOf {
  public static final String SERIALIZED_NAME_ADDRESS_LIST_ID = "addressListId";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LIST_ID)
  @javax.annotation.Nonnull
  private Integer addressListId;

  public RecipientAddressSourceOneOf() {
  }

  public RecipientAddressSourceOneOf addressListId(@javax.annotation.Nonnull Integer addressListId) {
    this.addressListId = addressListId;
    return this;
  }

  /**
   * Get addressListId
   * @return addressListId
   */
  @javax.annotation.Nonnull
  public Integer getAddressListId() {
    return addressListId;
  }

  public void setAddressListId(@javax.annotation.Nonnull Integer addressListId) {
    this.addressListId = addressListId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecipientAddressSourceOneOf recipientAddressSourceOneOf = (RecipientAddressSourceOneOf) o;
    return Objects.equals(this.addressListId, recipientAddressSourceOneOf.addressListId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressListId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecipientAddressSourceOneOf {\n");
    sb.append("    addressListId: ").append(toIndentedString(addressListId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("addressListId"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("addressListId"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RecipientAddressSourceOneOf
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RecipientAddressSourceOneOf.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RecipientAddressSourceOneOf is not found in the empty JSON string", RecipientAddressSourceOneOf.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RecipientAddressSourceOneOf.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RecipientAddressSourceOneOf` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RecipientAddressSourceOneOf.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RecipientAddressSourceOneOf.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RecipientAddressSourceOneOf' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RecipientAddressSourceOneOf> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RecipientAddressSourceOneOf.class));

       return (TypeAdapter<T>) new TypeAdapter<RecipientAddressSourceOneOf>() {
           @Override
           public void write(JsonWriter out, RecipientAddressSourceOneOf value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RecipientAddressSourceOneOf read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RecipientAddressSourceOneOf given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RecipientAddressSourceOneOf
   * @throws IOException if the JSON string is invalid with respect to RecipientAddressSourceOneOf
   */
  public static RecipientAddressSourceOneOf fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RecipientAddressSourceOneOf.class);
  }

  /**
   * Convert an instance of RecipientAddressSourceOneOf to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

