/*
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import java.util.Objects;
import com.c2m.model.Address;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.c2m.JSON;

/**
 * RecipientaddresssourceVariant2
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-12T23:35:58.244558479Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class RecipientaddresssourceVariant2 {
  public static final String SERIALIZED_NAME_MAPPING_ID = "mappingId";
  @SerializedName(SERIALIZED_NAME_MAPPING_ID)
  @javax.annotation.Nullable
  private Integer mappingId;

  public static final String SERIALIZED_NAME_ADDRESS_LIST = "addressList";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LIST)
  @javax.annotation.Nonnull
  private List<Address> addressList = new ArrayList<>();

  public static final String SERIALIZED_NAME_ADDRESS_LIST_NAME = "addressListName";
  @SerializedName(SERIALIZED_NAME_ADDRESS_LIST_NAME)
  @javax.annotation.Nullable
  private String addressListName;

  public RecipientaddresssourceVariant2() {
  }

  public RecipientaddresssourceVariant2 mappingId(@javax.annotation.Nullable Integer mappingId) {
    this.mappingId = mappingId;
    return this;
  }

  /**
   * Get mappingId
   * @return mappingId
   */
  @javax.annotation.Nullable
  public Integer getMappingId() {
    return mappingId;
  }

  public void setMappingId(@javax.annotation.Nullable Integer mappingId) {
    this.mappingId = mappingId;
  }


  public RecipientaddresssourceVariant2 addressList(@javax.annotation.Nonnull List<Address> addressList) {
    this.addressList = addressList;
    return this;
  }

  public RecipientaddresssourceVariant2 addAddressListItem(Address addressListItem) {
    if (this.addressList == null) {
      this.addressList = new ArrayList<>();
    }
    this.addressList.add(addressListItem);
    return this;
  }

  /**
   * Get addressList
   * @return addressList
   */
  @javax.annotation.Nonnull
  public List<Address> getAddressList() {
    return addressList;
  }

  public void setAddressList(@javax.annotation.Nonnull List<Address> addressList) {
    this.addressList = addressList;
  }


  public RecipientaddresssourceVariant2 addressListName(@javax.annotation.Nullable String addressListName) {
    this.addressListName = addressListName;
    return this;
  }

  /**
   * Get addressListName
   * @return addressListName
   */
  @javax.annotation.Nullable
  public String getAddressListName() {
    return addressListName;
  }

  public void setAddressListName(@javax.annotation.Nullable String addressListName) {
    this.addressListName = addressListName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecipientaddresssourceVariant2 recipientaddresssourceVariant2 = (RecipientaddresssourceVariant2) o;
    return Objects.equals(this.mappingId, recipientaddresssourceVariant2.mappingId) &&
        Objects.equals(this.addressList, recipientaddresssourceVariant2.addressList) &&
        Objects.equals(this.addressListName, recipientaddresssourceVariant2.addressListName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mappingId, addressList, addressListName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecipientaddresssourceVariant2 {\n");
    sb.append("    mappingId: ").append(toIndentedString(mappingId)).append("\n");
    sb.append("    addressList: ").append(toIndentedString(addressList)).append("\n");
    sb.append("    addressListName: ").append(toIndentedString(addressListName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("mappingId", "addressList", "addressListName"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("addressList"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to RecipientaddresssourceVariant2
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RecipientaddresssourceVariant2.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RecipientaddresssourceVariant2 is not found in the empty JSON string", RecipientaddresssourceVariant2.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RecipientaddresssourceVariant2.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RecipientaddresssourceVariant2` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RecipientaddresssourceVariant2.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("addressList").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `addressList` to be an array in the JSON string but got `%s`", jsonObj.get("addressList").toString()));
      }

      JsonArray jsonArrayaddressList = jsonObj.getAsJsonArray("addressList");
      // validate the required field `addressList` (array)
      for (int i = 0; i < jsonArrayaddressList.size(); i++) {
        Address.validateJsonElement(jsonArrayaddressList.get(i));
      };
      if ((jsonObj.get("addressListName") != null && !jsonObj.get("addressListName").isJsonNull()) && !jsonObj.get("addressListName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `addressListName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("addressListName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RecipientaddresssourceVariant2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RecipientaddresssourceVariant2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RecipientaddresssourceVariant2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RecipientaddresssourceVariant2.class));

       return (TypeAdapter<T>) new TypeAdapter<RecipientaddresssourceVariant2>() {
           @Override
           public void write(JsonWriter out, RecipientaddresssourceVariant2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RecipientaddresssourceVariant2 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of RecipientaddresssourceVariant2 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of RecipientaddresssourceVariant2
   * @throws IOException if the JSON string is invalid with respect to RecipientaddresssourceVariant2
   */
  public static RecipientaddresssourceVariant2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RecipientaddresssourceVariant2.class);
  }

  /**
   * Convert an instance of RecipientaddresssourceVariant2 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

