/*
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import java.util.Objects;
import com.c2m.model.JobOptions;
import com.c2m.model.PaymentDetails;
import com.c2m.model.SubmitMultiDocWithTemplateParamsRequestItemsInner;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.c2m.JSON;

/**
 * SubmitMultiDocParams
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-02T10:56:51.757820973Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class SubmitMultiDocParams {
  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  @javax.annotation.Nonnull
  private List<SubmitMultiDocWithTemplateParamsRequestItemsInner> items = new ArrayList<>();

  public static final String SERIALIZED_NAME_JOB_OPTIONS = "jobOptions";
  @SerializedName(SERIALIZED_NAME_JOB_OPTIONS)
  @javax.annotation.Nonnull
  private JobOptions jobOptions;

  public static final String SERIALIZED_NAME_PAYMENT_DETAILS = "paymentDetails";
  @SerializedName(SERIALIZED_NAME_PAYMENT_DETAILS)
  @javax.annotation.Nonnull
  private PaymentDetails paymentDetails;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public SubmitMultiDocParams() {
  }

  public SubmitMultiDocParams items(@javax.annotation.Nonnull List<SubmitMultiDocWithTemplateParamsRequestItemsInner> items) {
    this.items = items;
    return this;
  }

  public SubmitMultiDocParams addItemsItem(SubmitMultiDocWithTemplateParamsRequestItemsInner itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * Get items
   * @return items
   */
  @javax.annotation.Nonnull
  public List<SubmitMultiDocWithTemplateParamsRequestItemsInner> getItems() {
    return items;
  }

  public void setItems(@javax.annotation.Nonnull List<SubmitMultiDocWithTemplateParamsRequestItemsInner> items) {
    this.items = items;
  }


  public SubmitMultiDocParams jobOptions(@javax.annotation.Nonnull JobOptions jobOptions) {
    this.jobOptions = jobOptions;
    return this;
  }

  /**
   * Get jobOptions
   * @return jobOptions
   */
  @javax.annotation.Nonnull
  public JobOptions getJobOptions() {
    return jobOptions;
  }

  public void setJobOptions(@javax.annotation.Nonnull JobOptions jobOptions) {
    this.jobOptions = jobOptions;
  }


  public SubmitMultiDocParams paymentDetails(@javax.annotation.Nonnull PaymentDetails paymentDetails) {
    this.paymentDetails = paymentDetails;
    return this;
  }

  /**
   * Get paymentDetails
   * @return paymentDetails
   */
  @javax.annotation.Nonnull
  public PaymentDetails getPaymentDetails() {
    return paymentDetails;
  }

  public void setPaymentDetails(@javax.annotation.Nonnull PaymentDetails paymentDetails) {
    this.paymentDetails = paymentDetails;
  }


  public SubmitMultiDocParams tags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
    return this;
  }

  public SubmitMultiDocParams addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  public List<String> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmitMultiDocParams submitMultiDocParams = (SubmitMultiDocParams) o;
    return Objects.equals(this.items, submitMultiDocParams.items) &&
        Objects.equals(this.jobOptions, submitMultiDocParams.jobOptions) &&
        Objects.equals(this.paymentDetails, submitMultiDocParams.paymentDetails) &&
        Objects.equals(this.tags, submitMultiDocParams.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(items, jobOptions, paymentDetails, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmitMultiDocParams {\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    jobOptions: ").append(toIndentedString(jobOptions)).append("\n");
    sb.append("    paymentDetails: ").append(toIndentedString(paymentDetails)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("items", "jobOptions", "paymentDetails", "tags"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("items", "jobOptions", "paymentDetails"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SubmitMultiDocParams
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SubmitMultiDocParams.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SubmitMultiDocParams is not found in the empty JSON string", SubmitMultiDocParams.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SubmitMultiDocParams.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SubmitMultiDocParams` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SubmitMultiDocParams.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the json data is an array
      if (!jsonObj.get("items").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `items` to be an array in the JSON string but got `%s`", jsonObj.get("items").toString()));
      }

      JsonArray jsonArrayitems = jsonObj.getAsJsonArray("items");
      // validate the required field `items` (array)
      for (int i = 0; i < jsonArrayitems.size(); i++) {
        SubmitMultiDocWithTemplateParamsRequestItemsInner.validateJsonElement(jsonArrayitems.get(i));
      };
      // validate the required field `jobOptions`
      JobOptions.validateJsonElement(jsonObj.get("jobOptions"));
      // validate the required field `paymentDetails`
      PaymentDetails.validateJsonElement(jsonObj.get("paymentDetails"));
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull() && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubmitMultiDocParams.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubmitMultiDocParams' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubmitMultiDocParams> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubmitMultiDocParams.class));

       return (TypeAdapter<T>) new TypeAdapter<SubmitMultiDocParams>() {
           @Override
           public void write(JsonWriter out, SubmitMultiDocParams value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SubmitMultiDocParams read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SubmitMultiDocParams given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SubmitMultiDocParams
   * @throws IOException if the JSON string is invalid with respect to SubmitMultiDocParams
   */
  public static SubmitMultiDocParams fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubmitMultiDocParams.class);
  }

  /**
   * Convert an instance of SubmitMultiDocParams to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

