/*
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.model;

import java.util.Objects;
import com.c2m.model.JobOptions;
import com.c2m.model.PaymentDetails;
import com.c2m.model.ReturnAddress;
import com.c2m.model.ZipDocumentSource;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.c2m.JSON;

/**
 * SubmitMultiZipAddressCaptureParams
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-16T20:59:42.677965516Z[Etc/UTC]", comments = "Generator version: 7.15.0")
public class SubmitMultiZipAddressCaptureParams {
  public static final String SERIALIZED_NAME_JOB_TEMPLATE = "jobTemplate";
  @SerializedName(SERIALIZED_NAME_JOB_TEMPLATE)
  @javax.annotation.Nullable
  private String jobTemplate;

  public static final String SERIALIZED_NAME_ZIP_DOCUMENT_SOURCE = "zipDocumentSource";
  @SerializedName(SERIALIZED_NAME_ZIP_DOCUMENT_SOURCE)
  @javax.annotation.Nonnull
  private ZipDocumentSource zipDocumentSource;

  public static final String SERIALIZED_NAME_PAYMENT_DETAILS = "paymentDetails";
  @SerializedName(SERIALIZED_NAME_PAYMENT_DETAILS)
  @javax.annotation.Nullable
  private PaymentDetails paymentDetails;

  public static final String SERIALIZED_NAME_RETURN_ADDRESS = "returnAddress";
  @SerializedName(SERIALIZED_NAME_RETURN_ADDRESS)
  @javax.annotation.Nullable
  private ReturnAddress returnAddress;

  public static final String SERIALIZED_NAME_JOB_OPTIONS = "jobOptions";
  @SerializedName(SERIALIZED_NAME_JOB_OPTIONS)
  @javax.annotation.Nullable
  private JobOptions jobOptions;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  @javax.annotation.Nullable
  private List<String> tags = new ArrayList<>();

  public SubmitMultiZipAddressCaptureParams() {
  }

  public SubmitMultiZipAddressCaptureParams jobTemplate(@javax.annotation.Nullable String jobTemplate) {
    this.jobTemplate = jobTemplate;
    return this;
  }

  /**
   * Get jobTemplate
   * @return jobTemplate
   */
  @javax.annotation.Nullable
  public String getJobTemplate() {
    return jobTemplate;
  }

  public void setJobTemplate(@javax.annotation.Nullable String jobTemplate) {
    this.jobTemplate = jobTemplate;
  }


  public SubmitMultiZipAddressCaptureParams zipDocumentSource(@javax.annotation.Nonnull ZipDocumentSource zipDocumentSource) {
    this.zipDocumentSource = zipDocumentSource;
    return this;
  }

  /**
   * Get zipDocumentSource
   * @return zipDocumentSource
   */
  @javax.annotation.Nonnull
  public ZipDocumentSource getZipDocumentSource() {
    return zipDocumentSource;
  }

  public void setZipDocumentSource(@javax.annotation.Nonnull ZipDocumentSource zipDocumentSource) {
    this.zipDocumentSource = zipDocumentSource;
  }


  public SubmitMultiZipAddressCaptureParams paymentDetails(@javax.annotation.Nullable PaymentDetails paymentDetails) {
    this.paymentDetails = paymentDetails;
    return this;
  }

  /**
   * Get paymentDetails
   * @return paymentDetails
   */
  @javax.annotation.Nullable
  public PaymentDetails getPaymentDetails() {
    return paymentDetails;
  }

  public void setPaymentDetails(@javax.annotation.Nullable PaymentDetails paymentDetails) {
    this.paymentDetails = paymentDetails;
  }


  public SubmitMultiZipAddressCaptureParams returnAddress(@javax.annotation.Nullable ReturnAddress returnAddress) {
    this.returnAddress = returnAddress;
    return this;
  }

  /**
   * Get returnAddress
   * @return returnAddress
   */
  @javax.annotation.Nullable
  public ReturnAddress getReturnAddress() {
    return returnAddress;
  }

  public void setReturnAddress(@javax.annotation.Nullable ReturnAddress returnAddress) {
    this.returnAddress = returnAddress;
  }


  public SubmitMultiZipAddressCaptureParams jobOptions(@javax.annotation.Nullable JobOptions jobOptions) {
    this.jobOptions = jobOptions;
    return this;
  }

  /**
   * Get jobOptions
   * @return jobOptions
   */
  @javax.annotation.Nullable
  public JobOptions getJobOptions() {
    return jobOptions;
  }

  public void setJobOptions(@javax.annotation.Nullable JobOptions jobOptions) {
    this.jobOptions = jobOptions;
  }


  public SubmitMultiZipAddressCaptureParams tags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
    return this;
  }

  public SubmitMultiZipAddressCaptureParams addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<>();
    }
    this.tags.add(tagsItem);
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  public List<String> getTags() {
    return tags;
  }

  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = tags;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubmitMultiZipAddressCaptureParams submitMultiZipAddressCaptureParams = (SubmitMultiZipAddressCaptureParams) o;
    return Objects.equals(this.jobTemplate, submitMultiZipAddressCaptureParams.jobTemplate) &&
        Objects.equals(this.zipDocumentSource, submitMultiZipAddressCaptureParams.zipDocumentSource) &&
        Objects.equals(this.paymentDetails, submitMultiZipAddressCaptureParams.paymentDetails) &&
        Objects.equals(this.returnAddress, submitMultiZipAddressCaptureParams.returnAddress) &&
        Objects.equals(this.jobOptions, submitMultiZipAddressCaptureParams.jobOptions) &&
        Objects.equals(this.tags, submitMultiZipAddressCaptureParams.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobTemplate, zipDocumentSource, paymentDetails, returnAddress, jobOptions, tags);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubmitMultiZipAddressCaptureParams {\n");
    sb.append("    jobTemplate: ").append(toIndentedString(jobTemplate)).append("\n");
    sb.append("    zipDocumentSource: ").append(toIndentedString(zipDocumentSource)).append("\n");
    sb.append("    paymentDetails: ").append(toIndentedString(paymentDetails)).append("\n");
    sb.append("    returnAddress: ").append(toIndentedString(returnAddress)).append("\n");
    sb.append("    jobOptions: ").append(toIndentedString(jobOptions)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("jobTemplate", "zipDocumentSource", "paymentDetails", "returnAddress", "jobOptions", "tags"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("zipDocumentSource"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SubmitMultiZipAddressCaptureParams
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SubmitMultiZipAddressCaptureParams.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SubmitMultiZipAddressCaptureParams is not found in the empty JSON string", SubmitMultiZipAddressCaptureParams.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SubmitMultiZipAddressCaptureParams.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `SubmitMultiZipAddressCaptureParams` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SubmitMultiZipAddressCaptureParams.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("jobTemplate") != null && !jsonObj.get("jobTemplate").isJsonNull()) && !jsonObj.get("jobTemplate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `jobTemplate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("jobTemplate").toString()));
      }
      // validate the required field `zipDocumentSource`
      ZipDocumentSource.validateJsonElement(jsonObj.get("zipDocumentSource"));
      // validate the optional field `paymentDetails`
      if (jsonObj.get("paymentDetails") != null && !jsonObj.get("paymentDetails").isJsonNull()) {
        PaymentDetails.validateJsonElement(jsonObj.get("paymentDetails"));
      }
      // validate the optional field `returnAddress`
      if (jsonObj.get("returnAddress") != null && !jsonObj.get("returnAddress").isJsonNull()) {
        ReturnAddress.validateJsonElement(jsonObj.get("returnAddress"));
      }
      // validate the optional field `jobOptions`
      if (jsonObj.get("jobOptions") != null && !jsonObj.get("jobOptions").isJsonNull()) {
        JobOptions.validateJsonElement(jsonObj.get("jobOptions"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("tags") != null && !jsonObj.get("tags").isJsonNull() && !jsonObj.get("tags").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `tags` to be an array in the JSON string but got `%s`", jsonObj.get("tags").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubmitMultiZipAddressCaptureParams.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubmitMultiZipAddressCaptureParams' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubmitMultiZipAddressCaptureParams> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubmitMultiZipAddressCaptureParams.class));

       return (TypeAdapter<T>) new TypeAdapter<SubmitMultiZipAddressCaptureParams>() {
           @Override
           public void write(JsonWriter out, SubmitMultiZipAddressCaptureParams value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SubmitMultiZipAddressCaptureParams read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SubmitMultiZipAddressCaptureParams given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SubmitMultiZipAddressCaptureParams
   * @throws IOException if the JSON string is invalid with respect to SubmitMultiZipAddressCaptureParams
   */
  public static SubmitMultiZipAddressCaptureParams fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubmitMultiZipAddressCaptureParams.class);
  }

  /**
   * Convert an instance of SubmitMultiZipAddressCaptureParams to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

