/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models

import com.c2m.api.models.ExpirationDate

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param cardType 
 * @param cardNumber 
 * @param expirationDate 
 * @param cvv 
 */


data class CreditCardDetails (

    @Json(name = "cardType")
    val cardType: CreditCardDetails.CardType,

    @Json(name = "cardNumber")
    val cardNumber: kotlin.String,

    @Json(name = "expirationDate")
    val expirationDate: ExpirationDate,

    @Json(name = "cvv")
    val cvv: kotlin.Int

) {

    /**
     * 
     *
     * Values: visa,mastercard,discover,americanExpress
     */
    @JsonClass(generateAdapter = false)
    enum class CardType(val value: kotlin.String) {
        @Json(name = "visa") visa("visa"),
        @Json(name = "mastercard") mastercard("mastercard"),
        @Json(name = "discover") discover("discover"),
        @Json(name = "americanExpress") americanExpress("americanExpress");
    }

}

