/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.c2m.api.models

import com.c2m.api.models.RequestIdSource

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param requestId 
 * @param filename 
 */


data class DocSourceStandard (

    @Json(name = "requestId")
    val requestId: kotlin.Int,

    @Json(name = "filename")
    val filename: kotlin.String? = null

) {


}

