# coding: utf-8

"""
    C2M API v2

    API for submitting mailing jobs with various document routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ErrorType(str, Enum):
    """
    ErrorType
    """

    """
    allowed enum values
    """
    VALIDATIONERROR = 'ValidationError'
    AUTHENTICATIONERROR = 'AuthenticationError'
    AUTHORIZATIONERROR = 'AuthorizationError'
    RESOURCENOTFOUNDERROR = 'ResourceNotFoundError'
    SERVERERROR = 'ServerError'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ErrorType from a JSON string"""
        return cls(json.loads(json_str))


