# coding: utf-8

"""
    C2M API v2

    API for submitting mailing jobs with various document routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ErrorCode(str, Enum):
    """
    ErrorCode
    """

    """
    allowed enum values
    """
    MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD'
    INVALID_ONEOF = 'INVALID_ONEOF'
    INVALID_JSON = 'INVALID_JSON'
    MISSING_AUTH_HEADER = 'MISSING_AUTH_HEADER'
    INVALID_TOKEN = 'INVALID_TOKEN'
    EXPIRED_TOKEN = 'EXPIRED_TOKEN'
    INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS'
    ACCOUNT_SUSPENDED = 'ACCOUNT_SUSPENDED'
    JOB_NOT_FOUND = 'JOB_NOT_FOUND'
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND'
    INVALID_ENUM_VALUE = 'INVALID_ENUM_VALUE'
    MUTUAL_EXCLUSION_VIOLATION = 'MUTUAL_EXCLUSION_VIOLATION'
    INVALID_FORMAT = 'INVALID_FORMAT'
    SERVER_ERROR = 'SERVER_ERROR'
    DATABASE_ERROR = 'DATABASE_ERROR'
    EXTERNAL_SERVICE_ERROR = 'EXTERNAL_SERVICE_ERROR'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ErrorCode from a JSON string"""
        return cls(json.loads(json_str))


