/*
 * C2M API v2
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.c2m.api;

import com.c2m.ApiException;
import com.c2m.model.ErrorResponse;
import com.c2m.model.StandardResponse;
import com.c2m.model.SubmitMultiZipAddressCaptureParams;
import com.c2m.model.SubmitMultiZipParams;
import com.c2m.model.SubmitSinglePdfAddressCaptureParams;
import com.c2m.model.SubmitSinglePdfSplitAddressCaptureParams;
import com.c2m.model.SubmitSinglePdfSplitParams;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for JobsApi
 */
@Disabled
public class JobsApiTest {

    private final JobsApi api = new JobsApi();

    /**
     * Submit a multi zip addressCapture job
     *
     * Submits a multi zip addressCapture mailing job. The request body contains job parameters including document source, recipient address information, and payment details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void submitMultiZipAddressCaptureParamsTest() throws ApiException {
        SubmitMultiZipAddressCaptureParams submitMultiZipAddressCaptureParams = null;
        StandardResponse response = api.submitMultiZipAddressCaptureParams(submitMultiZipAddressCaptureParams);
        // TODO: test validations
    }

    /**
     * Submit a multi zip job
     *
     * Submits a multi zip mailing job. The request body contains job parameters including document source, recipient address information, and payment details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void submitMultiZipParamsTest() throws ApiException {
        SubmitMultiZipParams submitMultiZipParams = null;
        StandardResponse response = api.submitMultiZipParams(submitMultiZipParams);
        // TODO: test validations
    }

    /**
     * Submit a single pdf addressCapture job
     *
     * Submits a single pdf addressCapture mailing job. The request body contains job parameters including document source, recipient address information, and payment details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void submitSinglePdfAddressCaptureParamsTest() throws ApiException {
        SubmitSinglePdfAddressCaptureParams submitSinglePdfAddressCaptureParams = null;
        StandardResponse response = api.submitSinglePdfAddressCaptureParams(submitSinglePdfAddressCaptureParams);
        // TODO: test validations
    }

    /**
     * Submit a single pdf split addressCapture job
     *
     * Submits a single pdf split addressCapture mailing job. The request body contains job parameters including document source, recipient address information, and payment details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void submitSinglePdfSplitAddressCaptureParamsTest() throws ApiException {
        SubmitSinglePdfSplitAddressCaptureParams submitSinglePdfSplitAddressCaptureParams = null;
        StandardResponse response = api.submitSinglePdfSplitAddressCaptureParams(submitSinglePdfSplitAddressCaptureParams);
        // TODO: test validations
    }

    /**
     * Submit a single pdf split job
     *
     * Submits a single pdf split mailing job. The request body contains job parameters including document source, recipient address information, and payment details.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void submitSinglePdfSplitParamsTest() throws ApiException {
        SubmitSinglePdfSplitParams submitSinglePdfSplitParams = null;
        StandardResponse response = api.submitSinglePdfSplitParams(submitSinglePdfSplitParams);
        // TODO: test validations
    }

}
