// <auto-generated>
/*
 * C2M API v2
 *
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using C2M.Api.Client;

namespace C2M.Api.Model
{
    /// <summary>
    /// RecipientAddressSourceOneOf1
    /// </summary>
    public partial class RecipientAddressSourceOneOf1 : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RecipientAddressSourceOneOf1" /> class.
        /// </summary>
        /// <param name="recipientAddressByList">recipientAddressByList</param>
        [JsonConstructor]
        public RecipientAddressSourceOneOf1(RecipientAddressByList recipientAddressByList)
        {
            RecipientAddressByList = recipientAddressByList;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets RecipientAddressByList
        /// </summary>
        [JsonPropertyName("recipientAddressByList")]
        public RecipientAddressByList RecipientAddressByList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RecipientAddressSourceOneOf1 {\n");
            sb.Append("  RecipientAddressByList: ").Append(RecipientAddressByList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="RecipientAddressSourceOneOf1" />
    /// </summary>
    public class RecipientAddressSourceOneOf1JsonConverter : JsonConverter<RecipientAddressSourceOneOf1>
    {
        /// <summary>
        /// Deserializes json to <see cref="RecipientAddressSourceOneOf1" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override RecipientAddressSourceOneOf1 Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<RecipientAddressByList?> recipientAddressByList = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "recipientAddressByList":
                            recipientAddressByList = new Option<RecipientAddressByList?>(JsonSerializer.Deserialize<RecipientAddressByList>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!recipientAddressByList.IsSet)
                throw new ArgumentException("Property is required for class RecipientAddressSourceOneOf1.", nameof(recipientAddressByList));

            if (recipientAddressByList.IsSet && recipientAddressByList.Value == null)
                throw new ArgumentNullException(nameof(recipientAddressByList), "Property is not nullable for class RecipientAddressSourceOneOf1.");

            return new RecipientAddressSourceOneOf1(recipientAddressByList.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="RecipientAddressSourceOneOf1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="recipientAddressSourceOneOf1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, RecipientAddressSourceOneOf1 recipientAddressSourceOneOf1, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, recipientAddressSourceOneOf1, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="RecipientAddressSourceOneOf1" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="recipientAddressSourceOneOf1"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, RecipientAddressSourceOneOf1 recipientAddressSourceOneOf1, JsonSerializerOptions jsonSerializerOptions)
        {
            if (recipientAddressSourceOneOf1.RecipientAddressByList == null)
                throw new ArgumentNullException(nameof(recipientAddressSourceOneOf1.RecipientAddressByList), "Property is required for class RecipientAddressSourceOneOf1.");

            writer.WritePropertyName("recipientAddressByList");
            JsonSerializer.Serialize(writer, recipientAddressSourceOneOf1.RecipientAddressByList, jsonSerializerOptions);
        }
    }
}
