// <auto-generated>
/*
 * C2M API v2
 *
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using C2M.Api.Client;

namespace C2M.Api.Model
{
    /// <summary>
    /// SubmitDocParams
    /// </summary>
    public partial class SubmitDocParams : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitDocParams" /> class.
        /// </summary>
        /// <param name="docSourceAll">docSourceAll</param>
        /// <param name="recipientAddressSource">recipientAddressSource</param>
        /// <param name="jobTemplate">jobTemplate</param>
        /// <param name="paymentDetails">paymentDetails</param>
        /// <param name="returnAddress">returnAddress</param>
        /// <param name="jobOptions">jobOptions</param>
        /// <param name="tags">tags</param>
        [JsonConstructor]
        public SubmitDocParams(DocSourceAll docSourceAll, RecipientAddressSource recipientAddressSource, Option<string?> jobTemplate = default, Option<PaymentDetails?> paymentDetails = default, Option<ReturnAddress?> returnAddress = default, Option<JobOptions?> jobOptions = default, Option<List<string>?> tags = default)
        {
            DocSourceAll = docSourceAll;
            RecipientAddressSource = recipientAddressSource;
            JobTemplateOption = jobTemplate;
            PaymentDetailsOption = paymentDetails;
            ReturnAddressOption = returnAddress;
            JobOptionsOption = jobOptions;
            TagsOption = tags;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets DocSourceAll
        /// </summary>
        [JsonPropertyName("docSourceAll")]
        public DocSourceAll DocSourceAll { get; set; }

        /// <summary>
        /// Gets or Sets RecipientAddressSource
        /// </summary>
        [JsonPropertyName("recipientAddressSource")]
        public RecipientAddressSource RecipientAddressSource { get; set; }

        /// <summary>
        /// Used to track the state of JobTemplate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> JobTemplateOption { get; private set; }

        /// <summary>
        /// Gets or Sets JobTemplate
        /// </summary>
        [JsonPropertyName("jobTemplate")]
        public string? JobTemplate { get { return this.JobTemplateOption; } set { this.JobTemplateOption = new(value); } }

        /// <summary>
        /// Used to track the state of PaymentDetails
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<PaymentDetails?> PaymentDetailsOption { get; private set; }

        /// <summary>
        /// Gets or Sets PaymentDetails
        /// </summary>
        [JsonPropertyName("paymentDetails")]
        public PaymentDetails? PaymentDetails { get { return this.PaymentDetailsOption; } set { this.PaymentDetailsOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReturnAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ReturnAddress?> ReturnAddressOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReturnAddress
        /// </summary>
        [JsonPropertyName("returnAddress")]
        public ReturnAddress? ReturnAddress { get { return this.ReturnAddressOption; } set { this.ReturnAddressOption = new(value); } }

        /// <summary>
        /// Used to track the state of JobOptions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<JobOptions?> JobOptionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets JobOptions
        /// </summary>
        [JsonPropertyName("jobOptions")]
        public JobOptions? JobOptions { get { return this.JobOptionsOption; } set { this.JobOptionsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tags
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> TagsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [JsonPropertyName("tags")]
        public List<string>? Tags { get { return this.TagsOption; } set { this.TagsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SubmitDocParams {\n");
            sb.Append("  DocSourceAll: ").Append(DocSourceAll).Append("\n");
            sb.Append("  RecipientAddressSource: ").Append(RecipientAddressSource).Append("\n");
            sb.Append("  JobTemplate: ").Append(JobTemplate).Append("\n");
            sb.Append("  PaymentDetails: ").Append(PaymentDetails).Append("\n");
            sb.Append("  ReturnAddress: ").Append(ReturnAddress).Append("\n");
            sb.Append("  JobOptions: ").Append(JobOptions).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SubmitDocParams" />
    /// </summary>
    public class SubmitDocParamsJsonConverter : JsonConverter<SubmitDocParams>
    {
        /// <summary>
        /// Deserializes json to <see cref="SubmitDocParams" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SubmitDocParams Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DocSourceAll?> docSourceAll = default;
            Option<RecipientAddressSource?> recipientAddressSource = default;
            Option<string?> jobTemplate = default;
            Option<PaymentDetails?> paymentDetails = default;
            Option<ReturnAddress?> returnAddress = default;
            Option<JobOptions?> jobOptions = default;
            Option<List<string>?> tags = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "docSourceAll":
                            docSourceAll = new Option<DocSourceAll?>(JsonSerializer.Deserialize<DocSourceAll>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "recipientAddressSource":
                            recipientAddressSource = new Option<RecipientAddressSource?>(JsonSerializer.Deserialize<RecipientAddressSource>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "jobTemplate":
                            jobTemplate = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "paymentDetails":
                            paymentDetails = new Option<PaymentDetails?>(JsonSerializer.Deserialize<PaymentDetails>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "returnAddress":
                            returnAddress = new Option<ReturnAddress?>(JsonSerializer.Deserialize<ReturnAddress>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "jobOptions":
                            jobOptions = new Option<JobOptions?>(JsonSerializer.Deserialize<JobOptions>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "tags":
                            tags = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!docSourceAll.IsSet)
                throw new ArgumentException("Property is required for class SubmitDocParams.", nameof(docSourceAll));

            if (!recipientAddressSource.IsSet)
                throw new ArgumentException("Property is required for class SubmitDocParams.", nameof(recipientAddressSource));

            if (docSourceAll.IsSet && docSourceAll.Value == null)
                throw new ArgumentNullException(nameof(docSourceAll), "Property is not nullable for class SubmitDocParams.");

            if (recipientAddressSource.IsSet && recipientAddressSource.Value == null)
                throw new ArgumentNullException(nameof(recipientAddressSource), "Property is not nullable for class SubmitDocParams.");

            if (jobTemplate.IsSet && jobTemplate.Value == null)
                throw new ArgumentNullException(nameof(jobTemplate), "Property is not nullable for class SubmitDocParams.");

            if (paymentDetails.IsSet && paymentDetails.Value == null)
                throw new ArgumentNullException(nameof(paymentDetails), "Property is not nullable for class SubmitDocParams.");

            if (returnAddress.IsSet && returnAddress.Value == null)
                throw new ArgumentNullException(nameof(returnAddress), "Property is not nullable for class SubmitDocParams.");

            if (jobOptions.IsSet && jobOptions.Value == null)
                throw new ArgumentNullException(nameof(jobOptions), "Property is not nullable for class SubmitDocParams.");

            if (tags.IsSet && tags.Value == null)
                throw new ArgumentNullException(nameof(tags), "Property is not nullable for class SubmitDocParams.");

            return new SubmitDocParams(docSourceAll.Value!, recipientAddressSource.Value!, jobTemplate, paymentDetails, returnAddress, jobOptions, tags);
        }

        /// <summary>
        /// Serializes a <see cref="SubmitDocParams" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="submitDocParams"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SubmitDocParams submitDocParams, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, submitDocParams, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SubmitDocParams" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="submitDocParams"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SubmitDocParams submitDocParams, JsonSerializerOptions jsonSerializerOptions)
        {
            if (submitDocParams.DocSourceAll == null)
                throw new ArgumentNullException(nameof(submitDocParams.DocSourceAll), "Property is required for class SubmitDocParams.");

            if (submitDocParams.RecipientAddressSource == null)
                throw new ArgumentNullException(nameof(submitDocParams.RecipientAddressSource), "Property is required for class SubmitDocParams.");

            if (submitDocParams.JobTemplateOption.IsSet && submitDocParams.JobTemplate == null)
                throw new ArgumentNullException(nameof(submitDocParams.JobTemplate), "Property is required for class SubmitDocParams.");

            if (submitDocParams.PaymentDetailsOption.IsSet && submitDocParams.PaymentDetails == null)
                throw new ArgumentNullException(nameof(submitDocParams.PaymentDetails), "Property is required for class SubmitDocParams.");

            if (submitDocParams.ReturnAddressOption.IsSet && submitDocParams.ReturnAddress == null)
                throw new ArgumentNullException(nameof(submitDocParams.ReturnAddress), "Property is required for class SubmitDocParams.");

            if (submitDocParams.JobOptionsOption.IsSet && submitDocParams.JobOptions == null)
                throw new ArgumentNullException(nameof(submitDocParams.JobOptions), "Property is required for class SubmitDocParams.");

            if (submitDocParams.TagsOption.IsSet && submitDocParams.Tags == null)
                throw new ArgumentNullException(nameof(submitDocParams.Tags), "Property is required for class SubmitDocParams.");

            writer.WritePropertyName("docSourceAll");
            JsonSerializer.Serialize(writer, submitDocParams.DocSourceAll, jsonSerializerOptions);
            writer.WritePropertyName("recipientAddressSource");
            JsonSerializer.Serialize(writer, submitDocParams.RecipientAddressSource, jsonSerializerOptions);
            if (submitDocParams.JobTemplateOption.IsSet)
                writer.WriteString("jobTemplate", submitDocParams.JobTemplate);

            if (submitDocParams.PaymentDetailsOption.IsSet)
            {
                writer.WritePropertyName("paymentDetails");
                JsonSerializer.Serialize(writer, submitDocParams.PaymentDetails, jsonSerializerOptions);
            }
            if (submitDocParams.ReturnAddressOption.IsSet)
            {
                writer.WritePropertyName("returnAddress");
                JsonSerializer.Serialize(writer, submitDocParams.ReturnAddress, jsonSerializerOptions);
            }
            if (submitDocParams.JobOptionsOption.IsSet)
            {
                writer.WritePropertyName("jobOptions");
                JsonSerializer.Serialize(writer, submitDocParams.JobOptions, jsonSerializerOptions);
            }
            if (submitDocParams.TagsOption.IsSet)
            {
                writer.WritePropertyName("tags");
                JsonSerializer.Serialize(writer, submitDocParams.Tags, jsonSerializerOptions);
            }
        }
    }
}
