// <auto-generated>
/*
 * C2M API v2
 *
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using C2M.Api.Client;

namespace C2M.Api.Model
{
    /// <summary>
    /// ZipDocumentSourceOneOf
    /// </summary>
    public partial class ZipDocumentSourceOneOf : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ZipDocumentSourceOneOf" /> class.
        /// </summary>
        /// <param name="zipDocumentIdSource">zipDocumentIdSource</param>
        [JsonConstructor]
        public ZipDocumentSourceOneOf(ZipDocumentIdSource zipDocumentIdSource)
        {
            ZipDocumentIdSource = zipDocumentIdSource;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets ZipDocumentIdSource
        /// </summary>
        [JsonPropertyName("zipDocumentIdSource")]
        public ZipDocumentIdSource ZipDocumentIdSource { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ZipDocumentSourceOneOf {\n");
            sb.Append("  ZipDocumentIdSource: ").Append(ZipDocumentIdSource).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ZipDocumentSourceOneOf" />
    /// </summary>
    public class ZipDocumentSourceOneOfJsonConverter : JsonConverter<ZipDocumentSourceOneOf>
    {
        /// <summary>
        /// Deserializes json to <see cref="ZipDocumentSourceOneOf" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ZipDocumentSourceOneOf Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<ZipDocumentIdSource?> zipDocumentIdSource = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "zipDocumentIdSource":
                            zipDocumentIdSource = new Option<ZipDocumentIdSource?>(JsonSerializer.Deserialize<ZipDocumentIdSource>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!zipDocumentIdSource.IsSet)
                throw new ArgumentException("Property is required for class ZipDocumentSourceOneOf.", nameof(zipDocumentIdSource));

            if (zipDocumentIdSource.IsSet && zipDocumentIdSource.Value == null)
                throw new ArgumentNullException(nameof(zipDocumentIdSource), "Property is not nullable for class ZipDocumentSourceOneOf.");

            return new ZipDocumentSourceOneOf(zipDocumentIdSource.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="ZipDocumentSourceOneOf" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="zipDocumentSourceOneOf"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ZipDocumentSourceOneOf zipDocumentSourceOneOf, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, zipDocumentSourceOneOf, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ZipDocumentSourceOneOf" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="zipDocumentSourceOneOf"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ZipDocumentSourceOneOf zipDocumentSourceOneOf, JsonSerializerOptions jsonSerializerOptions)
        {
            if (zipDocumentSourceOneOf.ZipDocumentIdSource == null)
                throw new ArgumentNullException(nameof(zipDocumentSourceOneOf.ZipDocumentIdSource), "Property is required for class ZipDocumentSourceOneOf.");

            writer.WritePropertyName("zipDocumentIdSource");
            JsonSerializer.Serialize(writer, zipDocumentSourceOneOf.ZipDocumentIdSource, jsonSerializerOptions);
        }
    }
}
