=begin
#C2M API v2

#API for submitting mailing jobs with various document routing options

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'cgi'

module OpenapiClient
  class JobsApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Submit single document
    # Submits a mailing job for a single document to one or more recipients. The request body must include a document source, recipient address information, and payment details.
    # @param submit_doc_params [SubmitDocParams] 
    # @param [Hash] opts the optional parameters
    # @return [StandardResponse]
    def submit_doc_params(submit_doc_params, opts = {})
      data, _status_code, _headers = submit_doc_params_with_http_info(submit_doc_params, opts)
      data
    end

    # Submit single document
    # Submits a mailing job for a single document to one or more recipients. The request body must include a document source, recipient address information, and payment details.
    # @param submit_doc_params [SubmitDocParams] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(StandardResponse, Integer, Hash)>] StandardResponse data, response status code and response headers
    def submit_doc_params_with_http_info(submit_doc_params, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: JobsApi.submit_doc_params ...'
      end
      # verify the required parameter 'submit_doc_params' is set
      if @api_client.config.client_side_validation && submit_doc_params.nil?
        fail ArgumentError, "Missing the required parameter 'submit_doc_params' when calling JobsApi.submit_doc_params"
      end
      # resource path
      local_var_path = '/static'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(submit_doc_params)

      # return_type
      return_type = opts[:debug_return_type] || 'StandardResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"JobsApi.submit_doc_params",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: JobsApi#submit_doc_params\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Submit mail merge
    # Merges multiple documents into a single mailing sent to one recipient. Useful for creating document packets or multi-page letters.
    # @param submit_multi_doc_merge_params [SubmitMultiDocMergeParams] 
    # @param [Hash] opts the optional parameters
    # @return [StandardResponse]
    def submit_multi_doc_merge_params(submit_multi_doc_merge_params, opts = {})
      data, _status_code, _headers = submit_multi_doc_merge_params_with_http_info(submit_multi_doc_merge_params, opts)
      data
    end

    # Submit mail merge
    # Merges multiple documents into a single mailing sent to one recipient. Useful for creating document packets or multi-page letters.
    # @param submit_multi_doc_merge_params [SubmitMultiDocMergeParams] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(StandardResponse, Integer, Hash)>] StandardResponse data, response status code and response headers
    def submit_multi_doc_merge_params_with_http_info(submit_multi_doc_merge_params, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: JobsApi.submit_multi_doc_merge_params ...'
      end
      # verify the required parameter 'submit_multi_doc_merge_params' is set
      if @api_client.config.client_side_validation && submit_multi_doc_merge_params.nil?
        fail ArgumentError, "Missing the required parameter 'submit_multi_doc_merge_params' when calling JobsApi.submit_multi_doc_merge_params"
      end
      # resource path
      local_var_path = '/mail-merge'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(submit_multi_doc_merge_params)

      # return_type
      return_type = opts[:debug_return_type] || 'StandardResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"JobsApi.submit_multi_doc_merge_params",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: JobsApi#submit_multi_doc_merge_params\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Submit ZIP batch — address capture
    # Submits a ZIP-based mailing batch where recipient addresses are captured externally. No inline recipient addresses are required.
    # @param submit_multi_zip_address_capture_params [SubmitMultiZipAddressCaptureParams] 
    # @param [Hash] opts the optional parameters
    # @return [StandardResponse]
    def submit_multi_zip_address_capture_params(submit_multi_zip_address_capture_params, opts = {})
      data, _status_code, _headers = submit_multi_zip_address_capture_params_with_http_info(submit_multi_zip_address_capture_params, opts)
      data
    end

    # Submit ZIP batch — address capture
    # Submits a ZIP-based mailing batch where recipient addresses are captured externally. No inline recipient addresses are required.
    # @param submit_multi_zip_address_capture_params [SubmitMultiZipAddressCaptureParams] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(StandardResponse, Integer, Hash)>] StandardResponse data, response status code and response headers
    def submit_multi_zip_address_capture_params_with_http_info(submit_multi_zip_address_capture_params, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: JobsApi.submit_multi_zip_address_capture_params ...'
      end
      # verify the required parameter 'submit_multi_zip_address_capture_params' is set
      if @api_client.config.client_side_validation && submit_multi_zip_address_capture_params.nil?
        fail ArgumentError, "Missing the required parameter 'submit_multi_zip_address_capture_params' when calling JobsApi.submit_multi_zip_address_capture_params"
      end
      # resource path
      local_var_path = '/batch/zip/address-capture'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(submit_multi_zip_address_capture_params)

      # return_type
      return_type = opts[:debug_return_type] || 'StandardResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"JobsApi.submit_multi_zip_address_capture_params",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: JobsApi#submit_multi_zip_address_capture_params\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Submit ZIP batch
    # Submits multiple mailing jobs sourced from files inside a single ZIP archive. Each job item specifies which file within the ZIP and the recipient address.
    # @param submit_multi_zip_params [SubmitMultiZipParams] 
    # @param [Hash] opts the optional parameters
    # @return [StandardResponse]
    def submit_multi_zip_params(submit_multi_zip_params, opts = {})
      data, _status_code, _headers = submit_multi_zip_params_with_http_info(submit_multi_zip_params, opts)
      data
    end

    # Submit ZIP batch
    # Submits multiple mailing jobs sourced from files inside a single ZIP archive. Each job item specifies which file within the ZIP and the recipient address.
    # @param submit_multi_zip_params [SubmitMultiZipParams] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(StandardResponse, Integer, Hash)>] StandardResponse data, response status code and response headers
    def submit_multi_zip_params_with_http_info(submit_multi_zip_params, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: JobsApi.submit_multi_zip_params ...'
      end
      # verify the required parameter 'submit_multi_zip_params' is set
      if @api_client.config.client_side_validation && submit_multi_zip_params.nil?
        fail ArgumentError, "Missing the required parameter 'submit_multi_zip_params' when calling JobsApi.submit_multi_zip_params"
      end
      # resource path
      local_var_path = '/batch/zip'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(submit_multi_zip_params)

      # return_type
      return_type = opts[:debug_return_type] || 'StandardResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"JobsApi.submit_multi_zip_params",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: JobsApi#submit_multi_zip_params\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Submit single document — address capture
    # Submits a mailing job for a single PDF where recipient addresses are captured from the document via OCR. No inline recipient address is required.
    # @param submit_single_pdf_address_capture_params [SubmitSinglePdfAddressCaptureParams] 
    # @param [Hash] opts the optional parameters
    # @return [StandardResponse]
    def submit_single_pdf_address_capture_params(submit_single_pdf_address_capture_params, opts = {})
      data, _status_code, _headers = submit_single_pdf_address_capture_params_with_http_info(submit_single_pdf_address_capture_params, opts)
      data
    end

    # Submit single document — address capture
    # Submits a mailing job for a single PDF where recipient addresses are captured from the document via OCR. No inline recipient address is required.
    # @param submit_single_pdf_address_capture_params [SubmitSinglePdfAddressCaptureParams] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(StandardResponse, Integer, Hash)>] StandardResponse data, response status code and response headers
    def submit_single_pdf_address_capture_params_with_http_info(submit_single_pdf_address_capture_params, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: JobsApi.submit_single_pdf_address_capture_params ...'
      end
      # verify the required parameter 'submit_single_pdf_address_capture_params' is set
      if @api_client.config.client_side_validation && submit_single_pdf_address_capture_params.nil?
        fail ArgumentError, "Missing the required parameter 'submit_single_pdf_address_capture_params' when calling JobsApi.submit_single_pdf_address_capture_params"
      end
      # resource path
      local_var_path = '/static/address-capture'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(submit_single_pdf_address_capture_params)

      # return_type
      return_type = opts[:debug_return_type] || 'StandardResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"JobsApi.submit_single_pdf_address_capture_params",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: JobsApi#submit_single_pdf_address_capture_params\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Submit PDF split — address capture
    # Splits a single PDF into page ranges where recipient addresses are captured from the PDF. No inline recipient addresses are required.
    # @param submit_single_pdf_split_address_capture_params [SubmitSinglePdfSplitAddressCaptureParams] 
    # @param [Hash] opts the optional parameters
    # @return [StandardResponse]
    def submit_single_pdf_split_address_capture_params(submit_single_pdf_split_address_capture_params, opts = {})
      data, _status_code, _headers = submit_single_pdf_split_address_capture_params_with_http_info(submit_single_pdf_split_address_capture_params, opts)
      data
    end

    # Submit PDF split — address capture
    # Splits a single PDF into page ranges where recipient addresses are captured from the PDF. No inline recipient addresses are required.
    # @param submit_single_pdf_split_address_capture_params [SubmitSinglePdfSplitAddressCaptureParams] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(StandardResponse, Integer, Hash)>] StandardResponse data, response status code and response headers
    def submit_single_pdf_split_address_capture_params_with_http_info(submit_single_pdf_split_address_capture_params, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: JobsApi.submit_single_pdf_split_address_capture_params ...'
      end
      # verify the required parameter 'submit_single_pdf_split_address_capture_params' is set
      if @api_client.config.client_side_validation && submit_single_pdf_split_address_capture_params.nil?
        fail ArgumentError, "Missing the required parameter 'submit_single_pdf_split_address_capture_params' when calling JobsApi.submit_single_pdf_split_address_capture_params"
      end
      # resource path
      local_var_path = '/batch/split/address-capture'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(submit_single_pdf_split_address_capture_params)

      # return_type
      return_type = opts[:debug_return_type] || 'StandardResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"JobsApi.submit_single_pdf_split_address_capture_params",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: JobsApi#submit_single_pdf_split_address_capture_params\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Submit PDF split
    # Splits a single PDF into page ranges and mails each range to a different recipient. Each job item specifies page range and recipient address.
    # @param submit_single_pdf_split_params [SubmitSinglePdfSplitParams] 
    # @param [Hash] opts the optional parameters
    # @return [StandardResponse]
    def submit_single_pdf_split_params(submit_single_pdf_split_params, opts = {})
      data, _status_code, _headers = submit_single_pdf_split_params_with_http_info(submit_single_pdf_split_params, opts)
      data
    end

    # Submit PDF split
    # Splits a single PDF into page ranges and mails each range to a different recipient. Each job item specifies page range and recipient address.
    # @param submit_single_pdf_split_params [SubmitSinglePdfSplitParams] 
    # @param [Hash] opts the optional parameters
    # @return [Array<(StandardResponse, Integer, Hash)>] StandardResponse data, response status code and response headers
    def submit_single_pdf_split_params_with_http_info(submit_single_pdf_split_params, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: JobsApi.submit_single_pdf_split_params ...'
      end
      # verify the required parameter 'submit_single_pdf_split_params' is set
      if @api_client.config.client_side_validation && submit_single_pdf_split_params.nil?
        fail ArgumentError, "Missing the required parameter 'submit_single_pdf_split_params' when calling JobsApi.submit_single_pdf_split_params"
      end
      # resource path
      local_var_path = '/batch/split'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(submit_single_pdf_split_params)

      # return_type
      return_type = opts[:debug_return_type] || 'StandardResponse'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['bearerAuth']

      new_options = opts.merge(
        :operation => :"JobsApi.submit_single_pdf_split_params",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: JobsApi#submit_single_pdf_split_params\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
