/*
 * C2M API v2
 *
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using C2M.Api.Model;
using C2M.Api.Client;
using System.Reflection;

namespace C2M.Api.Test.Model
{
    /// <summary>
    ///  Class for testing DocSourceZipFileRefOneOf1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocSourceZipFileRefOneOf1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocSourceZipFileRefOneOf1
        //private DocSourceZipFileRefOneOf1 instance;

        public DocSourceZipFileRefOneOf1Tests()
        {
            // TODO uncomment below to create an instance of DocSourceZipFileRefOneOf1
            //instance = new DocSourceZipFileRefOneOf1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocSourceZipFileRefOneOf1
        /// </summary>
        [Fact]
        public void DocSourceZipFileRefOneOf1InstanceTest()
        {
            // TODO uncomment below to test "IsType" DocSourceZipFileRefOneOf1
            //Assert.IsType<DocSourceZipFileRefOneOf1>(instance);
        }

        /// <summary>
        /// Test the property 'ZipRequestIdOnly'
        /// </summary>
        [Fact]
        public void ZipRequestIdOnlyTest()
        {
            // TODO unit test for the property 'ZipRequestIdOnly'
        }
    }
}
