/*
 * C2M API v2
 *
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using C2M.Api.Model;
using C2M.Api.Client;
using System.Reflection;

namespace C2M.Api.Test.Model
{
    /// <summary>
    ///  Class for testing InvoiceDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvoiceDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InvoiceDetails
        //private InvoiceDetails instance;

        public InvoiceDetailsTests()
        {
            // TODO uncomment below to create an instance of InvoiceDetails
            //instance = new InvoiceDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvoiceDetails
        /// </summary>
        [Fact]
        public void InvoiceDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" InvoiceDetails
            //Assert.IsType<InvoiceDetails>(instance);
        }

        /// <summary>
        /// Test the property 'InvoiceNumber'
        /// </summary>
        [Fact]
        public void InvoiceNumberTest()
        {
            // TODO unit test for the property 'InvoiceNumber'
        }

        /// <summary>
        /// Test the property 'AmountDue'
        /// </summary>
        [Fact]
        public void AmountDueTest()
        {
            // TODO unit test for the property 'AmountDue'
        }
    }
}
