/*
 * C2M API v2
 *
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using C2M.Api.Model;
using C2M.Api.Client;
using System.Reflection;

namespace C2M.Api.Test.Model
{
    /// <summary>
    ///  Class for testing MailClass
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MailClassTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MailClass
        //private MailClass instance;

        public MailClassTests()
        {
            // TODO uncomment below to create an instance of MailClass
            //instance = new MailClass();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MailClass
        /// </summary>
        [Fact]
        public void MailClassInstanceTest()
        {
            // TODO uncomment below to test "IsType" MailClass
            //Assert.IsType<MailClass>(instance);
        }
    }
}
