/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using C2M.Api.Model;
using C2M.Api.Client;
using System.Reflection;

namespace C2M.Api.Test.Model
{
    /// <summary>
    ///  Class for testing MergeDocumentRef
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MergeDocumentRefTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MergeDocumentRef
        //private MergeDocumentRef instance;

        public MergeDocumentRefTests()
        {
            // TODO uncomment below to create an instance of MergeDocumentRef
            //instance = new MergeDocumentRef();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MergeDocumentRef
        /// </summary>
        [Fact]
        public void MergeDocumentRefInstanceTest()
        {
            // TODO uncomment below to test "IsType" MergeDocumentRef
            //Assert.IsType<MergeDocumentRef>(instance);
        }
    }
}
