/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using C2M.Api.Model;
using C2M.Api.Client;
using System.Reflection;

namespace C2M.Api.Test.Model
{
    /// <summary>
    ///  Class for testing MultiDocJobItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MultiDocJobItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MultiDocJobItem
        //private MultiDocJobItem instance;

        public MultiDocJobItemTests()
        {
            // TODO uncomment below to create an instance of MultiDocJobItem
            //instance = new MultiDocJobItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MultiDocJobItem
        /// </summary>
        [Fact]
        public void MultiDocJobItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" MultiDocJobItem
            //Assert.IsType<MultiDocJobItem>(instance);
        }

        /// <summary>
        /// Test the property 'DocSourceAll'
        /// </summary>
        [Fact]
        public void DocSourceAllTest()
        {
            // TODO unit test for the property 'DocSourceAll'
        }

        /// <summary>
        /// Test the property 'RecipientAddressSource'
        /// </summary>
        [Fact]
        public void RecipientAddressSourceTest()
        {
            // TODO unit test for the property 'RecipientAddressSource'
        }

        /// <summary>
        /// Test the property 'JobTemplate'
        /// </summary>
        [Fact]
        public void JobTemplateTest()
        {
            // TODO unit test for the property 'JobTemplate'
        }
    }
}
