/*
 * C2M API v2
 *
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using C2M.Api.Model;
using C2M.Api.Client;
using System.Reflection;

namespace C2M.Api.Test.Model
{
    /// <summary>
    ///  Class for testing SubmitSinglePdfSplitAddressCaptureParams
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubmitSinglePdfSplitAddressCaptureParamsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubmitSinglePdfSplitAddressCaptureParams
        //private SubmitSinglePdfSplitAddressCaptureParams instance;

        public SubmitSinglePdfSplitAddressCaptureParamsTests()
        {
            // TODO uncomment below to create an instance of SubmitSinglePdfSplitAddressCaptureParams
            //instance = new SubmitSinglePdfSplitAddressCaptureParams();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubmitSinglePdfSplitAddressCaptureParams
        /// </summary>
        [Fact]
        public void SubmitSinglePdfSplitAddressCaptureParamsInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubmitSinglePdfSplitAddressCaptureParams
            //Assert.IsType<SubmitSinglePdfSplitAddressCaptureParams>(instance);
        }

        /// <summary>
        /// Test the property 'DocSourceStandard'
        /// </summary>
        [Fact]
        public void DocSourceStandardTest()
        {
            // TODO unit test for the property 'DocSourceStandard'
        }

        /// <summary>
        /// Test the property 'PdfSplitJobsNoAddress'
        /// </summary>
        [Fact]
        public void PdfSplitJobsNoAddressTest()
        {
            // TODO unit test for the property 'PdfSplitJobsNoAddress'
        }

        /// <summary>
        /// Test the property 'JobTemplate'
        /// </summary>
        [Fact]
        public void JobTemplateTest()
        {
            // TODO unit test for the property 'JobTemplate'
        }

        /// <summary>
        /// Test the property 'PaymentDetails'
        /// </summary>
        [Fact]
        public void PaymentDetailsTest()
        {
            // TODO unit test for the property 'PaymentDetails'
        }

        /// <summary>
        /// Test the property 'ReturnAddress'
        /// </summary>
        [Fact]
        public void ReturnAddressTest()
        {
            // TODO unit test for the property 'ReturnAddress'
        }

        /// <summary>
        /// Test the property 'JobOptions'
        /// </summary>
        [Fact]
        public void JobOptionsTest()
        {
            // TODO unit test for the property 'JobOptions'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }
    }
}
