/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using C2M.Api.Model;
using C2M.Api.Client;
using System.Reflection;

namespace C2M.Api.Test.Model
{
    /// <summary>
    ///  Class for testing ZipDocumentIdSource
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ZipDocumentIdSourceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ZipDocumentIdSource
        //private ZipDocumentIdSource instance;

        public ZipDocumentIdSourceTests()
        {
            // TODO uncomment below to create an instance of ZipDocumentIdSource
            //instance = new ZipDocumentIdSource();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ZipDocumentIdSource
        /// </summary>
        [Fact]
        public void ZipDocumentIdSourceInstanceTest()
        {
            // TODO uncomment below to test "IsType" ZipDocumentIdSource
            //Assert.IsType<ZipDocumentIdSource>(instance);
        }

        /// <summary>
        /// Test the property 'ZipDocumentId'
        /// </summary>
        [Fact]
        public void ZipDocumentIdTest()
        {
            // TODO unit test for the property 'ZipDocumentId'
        }

        /// <summary>
        /// Test the property 'Filename'
        /// </summary>
        [Fact]
        public void FilenameTest()
        {
            // TODO unit test for the property 'Filename'
        }
    }
}
