# coding: utf-8

"""
    C2M API v2

    API for submitting mailing jobs with various document routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from c2m_api.models.recipient_address_by_single import RecipientAddressBySingle

class TestRecipientAddressBySingle(unittest.TestCase):
    """RecipientAddressBySingle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecipientAddressBySingle:
        """Test RecipientAddressBySingle
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecipientAddressBySingle`
        """
        model = RecipientAddressBySingle()
        if include_optional:
            return RecipientAddressBySingle(
                mapping_id = 56,
                single_address = c2m_api.models.address.address(
                    first_name = '', 
                    last_name = '', 
                    address1 = '', 
                    city = '', 
                    state = '', 
                    zip = '', 
                    country = '', 
                    address2 = '', 
                    address3 = '', 
                    foo1 = '', 
                    foo2 = '', ),
                address_name = ''
            )
        else:
            return RecipientAddressBySingle(
                single_address = c2m_api.models.address.address(
                    first_name = '', 
                    last_name = '', 
                    address1 = '', 
                    city = '', 
                    state = '', 
                    zip = '', 
                    country = '', 
                    address2 = '', 
                    address3 = '', 
                    foo1 = '', 
                    foo2 = '', ),
        )
        """

    def testRecipientAddressBySingle(self):
        """Test RecipientAddressBySingle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
