# coding: utf-8

"""
    C2M API v2

    API for submitting mailing jobs with various document routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from c2m_api.models.print_option import PrintOption

class TestPrintOption(unittest.TestCase):
    """PrintOption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrintOption(self):
        """Test PrintOption"""
        # inst = PrintOption()

if __name__ == '__main__':
    unittest.main()
