# coding: utf-8

"""
    C2M API v2 - Auth Overlay

    API for submitting documents with various routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from c2m_api.models.merge_document_ref import MergeDocumentRef

class TestMergeDocumentRef(unittest.TestCase):
    """MergeDocumentRef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MergeDocumentRef:
        """Test MergeDocumentRef
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MergeDocumentRef`
        """
        model = MergeDocumentRef()
        if include_optional:
            return MergeDocumentRef(
                request_id = 56,
                filename = ''
            )
        else:
            return MergeDocumentRef(
                request_id = 56,
        )
        """

    def testMergeDocumentRef(self):
        """Test MergeDocumentRef"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
