# coding: utf-8

"""
    C2M API v2

    API for submitting mailing jobs with various document routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from c2m_api.models.short_token_request import ShortTokenRequest

class TestShortTokenRequest(unittest.TestCase):
    """ShortTokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShortTokenRequest:
        """Test ShortTokenRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShortTokenRequest`
        """
        model = ShortTokenRequest()
        if include_optional:
            return ShortTokenRequest(
                long_token = '',
                scopes = [
                    ''
                    ]
            )
        else:
            return ShortTokenRequest(
        )
        """

    def testShortTokenRequest(self):
        """Test ShortTokenRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
