# coding: utf-8

"""
    C2M API v2

    API for submitting mailing jobs with various document routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from c2m_api.models.doc_source_standard_one_of import DocSourceStandardOneOf

class TestDocSourceStandardOneOf(unittest.TestCase):
    """DocSourceStandardOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocSourceStandardOneOf:
        """Test DocSourceStandardOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocSourceStandardOneOf`
        """
        model = DocSourceStandardOneOf()
        if include_optional:
            return DocSourceStandardOneOf(
                document_id_source = c2m_api.models.document_id_source.documentIdSource(
                    document_id = 56, )
            )
        else:
            return DocSourceStandardOneOf(
                document_id_source = c2m_api.models.document_id_source.documentIdSource(
                    document_id = 56, ),
        )
        """

    def testDocSourceStandardOneOf(self):
        """Test DocSourceStandardOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
