# coding: utf-8

"""
    C2M API v2

    API for submitting mailing jobs with various document routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from c2m_api.models.multi_zip_job_item import MultiZipJobItem

class TestMultiZipJobItem(unittest.TestCase):
    """MultiZipJobItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MultiZipJobItem:
        """Test MultiZipJobItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MultiZipJobItem`
        """
        model = MultiZipJobItem()
        if include_optional:
            return MultiZipJobItem(
                job_template = '',
                doc_source_zip_file = None,
                recipient_address_source = None
            )
        else:
            return MultiZipJobItem(
                doc_source_zip_file = None,
                recipient_address_source = None,
        )
        """

    def testMultiZipJobItem(self):
        """Test MultiZipJobItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
