# coding: utf-8

"""
    C2M API v2

    API for submitting mailing jobs with various document routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from c2m_api.models.doc_source_standard_one_of1 import DocSourceStandardOneOf1

class TestDocSourceStandardOneOf1(unittest.TestCase):
    """DocSourceStandardOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocSourceStandardOneOf1:
        """Test DocSourceStandardOneOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocSourceStandardOneOf1`
        """
        model = DocSourceStandardOneOf1()
        if include_optional:
            return DocSourceStandardOneOf1(
                request_id_source = c2m_api.models.request_id_source.requestIdSource(
                    request_id = 56, 
                    filename = '', )
            )
        else:
            return DocSourceStandardOneOf1(
                request_id_source = c2m_api.models.request_id_source.requestIdSource(
                    request_id = 56, 
                    filename = '', ),
        )
        """

    def testDocSourceStandardOneOf1(self):
        """Test DocSourceStandardOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
