# coding: utf-8

"""
    C2M API v2 - Auth Overlay

    API for submitting documents with various routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from c2m_api.models.payment_details import PaymentDetails

class TestPaymentDetails(unittest.TestCase):
    """PaymentDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentDetails:
        """Test PaymentDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentDetails`
        """
        model = PaymentDetails()
        if include_optional:
            return PaymentDetails(
                credit_card_details = c2m_api.models.credit_card_details.creditCardDetails(
                    card_type = 'visa', 
                    card_number = '', 
                    expiration_date = c2m_api.models.expiration_date.expirationDate(
                        month = 56, 
                        year = 56, ), 
                    cvv = 56, ),
                invoice_details = c2m_api.models.invoice_details.invoiceDetails(
                    invoice_number = '', 
                    amount_due = 1.337, ),
                ach_details = c2m_api.models.ach_details.achDetails(
                    routing_number = '', 
                    account_number = '', 
                    check_digit = 56, ),
                credit_amount = c2m_api.models.credit_amount.creditAmount(
                    amount = 1.337, 
                    currency = 'USD', )
            )
        else:
            return PaymentDetails(
                credit_card_details = c2m_api.models.credit_card_details.creditCardDetails(
                    card_type = 'visa', 
                    card_number = '', 
                    expiration_date = c2m_api.models.expiration_date.expirationDate(
                        month = 56, 
                        year = 56, ), 
                    cvv = 56, ),
                invoice_details = c2m_api.models.invoice_details.invoiceDetails(
                    invoice_number = '', 
                    amount_due = 1.337, ),
                ach_details = c2m_api.models.ach_details.achDetails(
                    routing_number = '', 
                    account_number = '', 
                    check_digit = 56, ),
                credit_amount = c2m_api.models.credit_amount.creditAmount(
                    amount = 1.337, 
                    currency = 'USD', ),
        )
        """

    def testPaymentDetails(self):
        """Test PaymentDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
