# coding: utf-8

"""
    C2M API v2

    API for submitting mailing jobs with various document routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from c2m_api.api.recommended_api import RecommendedApi


class TestRecommendedApi(unittest.TestCase):
    """RecommendedApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecommendedApi()

    def tearDown(self) -> None:
        pass

    def test_submit_multi_doc_merge_params(self) -> None:
        """Test case for submit_multi_doc_merge_params

        Submit a multi doc merge job
        """
        pass

    def test_submit_multi_doc_params(self) -> None:
        """Test case for submit_multi_doc_params

        Submit a multi doc job
        """
        pass

    def test_submit_single_doc_params(self) -> None:
        """Test case for submit_single_doc_params

        Submit a single doc job
        """
        pass


if __name__ == '__main__':
    unittest.main()
