# coding: utf-8

"""
    C2M API v2

    API for submitting mailing jobs with various document routing options

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from c2m_api.models.credit_card_details import CreditCardDetails

class TestCreditCardDetails(unittest.TestCase):
    """CreditCardDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreditCardDetails:
        """Test CreditCardDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreditCardDetails`
        """
        model = CreditCardDetails()
        if include_optional:
            return CreditCardDetails(
                card_type = 'visa',
                card_number = '',
                expiration_date = c2m_api.models.expiration_date.expirationDate(
                    month = 56, 
                    year = 56, ),
                cvv = 56
            )
        else:
            return CreditCardDetails(
                card_type = 'visa',
                card_number = '',
                expiration_date = c2m_api.models.expiration_date.expirationDate(
                    month = 56, 
                    year = 56, ),
                cvv = 56,
        )
        """

    def testCreditCardDetails(self):
        """Test CreditCardDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
