=begin
#C2M API v2

#API for submitting mailing jobs with various document routing options

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::InvoiceDetails
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::InvoiceDetails do
  let(:instance) { OpenapiClient::InvoiceDetails.new }

  describe 'test an instance of InvoiceDetails' do
    it 'should create an instance of InvoiceDetails' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::InvoiceDetails)
    end
  end

  describe 'test attribute "invoice_number"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  describe 'test attribute "amount_due"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
