/*
 * C2M API v2 - Auth Overlay
 *
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DocumentSource {
    DocumentIdSource(i32),
    RequestIdSource(Box<models::RequestIdSource>),
    UrlSource(String),
    ZipDocumentIdSource(Box<models::ZipDocumentIdSource>),
    ZipRequestIdSource(Box<models::ZipRequestIdSource>),
}

impl Default for DocumentSource {
    fn default() -> Self {
        Self::DocumentIdSource(Default::default())
    }
}

