/*
 * C2M API v2
 *
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Priority {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "rush")]
    Rush,
    #[serde(rename = "overnight")]
    Overnight,

}

impl std::fmt::Display for Priority {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Standard => write!(f, "standard"),
            Self::Rush => write!(f, "rush"),
            Self::Overnight => write!(f, "overnight"),
        }
    }
}

impl Default for Priority {
    fn default() -> Priority {
        Self::Standard
    }
}

