/*
 * C2M API v2
 *
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProductionTime {
    #[serde(rename = "next_day")]
    NextDay,
    #[serde(rename = "two_day")]
    TwoDay,
    #[serde(rename = "three_day")]
    ThreeDay,
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "same_day")]
    SameDay,

}

impl std::fmt::Display for ProductionTime {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NextDay => write!(f, "next_day"),
            Self::TwoDay => write!(f, "two_day"),
            Self::ThreeDay => write!(f, "three_day"),
            Self::Standard => write!(f, "standard"),
            Self::SameDay => write!(f, "same_day"),
        }
    }
}

impl Default for ProductionTime {
    fn default() -> ProductionTime {
        Self::NextDay
    }
}

