/*
 * C2M API v2
 *
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitMultiZipParams {
    #[serde(rename = "docSourceZipFileRef")]
    pub doc_source_zip_file_ref: Box<models::DocSourceZipFileRef>,
    #[serde(rename = "multiZipJobs")]
    pub multi_zip_jobs: Vec<models::MultiZipJobItem>,
    #[serde(rename = "paymentDetails", skip_serializing_if = "Option::is_none")]
    pub payment_details: Option<Box<models::PaymentDetails>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl SubmitMultiZipParams {
    pub fn new(doc_source_zip_file_ref: models::DocSourceZipFileRef, multi_zip_jobs: Vec<models::MultiZipJobItem>) -> SubmitMultiZipParams {
        SubmitMultiZipParams {
            doc_source_zip_file_ref: Box::new(doc_source_zip_file_ref),
            multi_zip_jobs,
            payment_details: None,
            tags: None,
        }
    }
}

