/*
 * C2M API v2
 *
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ZipDocumentIdOnly {
    #[serde(rename = "zipDocumentId")]
    pub zip_document_id: i32,
}

impl ZipDocumentIdOnly {
    pub fn new(zip_document_id: i32) -> ZipDocumentIdOnly {
        ZipDocumentIdOnly {
            zip_document_id,
        }
    }
}

