<?php
/**
 * ErrorType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  C2MApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * C2M API v2
 *
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace C2MApi\Model;
use \C2MApi\ObjectSerializer;

/**
 * ErrorType Class Doc Comment
 *
 * @category Class
 * @package  C2MApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ErrorType
{
    /**
     * Possible values of this enum
     */
    public const VALIDATION_ERROR = 'ValidationError';

    public const AUTHENTICATION_ERROR = 'AuthenticationError';

    public const AUTHORIZATION_ERROR = 'AuthorizationError';

    public const RESOURCE_NOT_FOUND_ERROR = 'ResourceNotFoundError';

    public const SERVER_ERROR = 'ServerError';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::VALIDATION_ERROR,
            self::AUTHENTICATION_ERROR,
            self::AUTHORIZATION_ERROR,
            self::RESOURCE_NOT_FOUND_ERROR,
            self::SERVER_ERROR
        ];
    }
}


