<?php
/**
 * PrintOption
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  C2MApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * C2M API v2
 *
 * API for submitting mailing jobs with various document routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace C2MApi\Model;
use \C2MApi\ObjectSerializer;

/**
 * PrintOption Class Doc Comment
 *
 * @category Class
 * @package  C2MApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PrintOption
{
    /**
     * Possible values of this enum
     */
    public const DOUBLE_SIDED = 'double_sided';

    public const SINGLE_SIDED = 'single_sided';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DOUBLE_SIDED,
            self::SINGLE_SIDED
        ];
    }
}


