=begin
#C2M API v2 - Auth Overlay

#API for submitting documents with various routing options

The version of the OpenAPI document: 2.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.15.0

=end

require 'date'
require 'time'

module OpenapiClient
  class JobOptions
    attr_accessor :document_class

    attr_accessor :layout

    attr_accessor :production_time

    attr_accessor :envelope

    attr_accessor :color

    attr_accessor :paper_type

    attr_accessor :print_option

    attr_accessor :mail_class

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'document_class' => :'documentClass',
        :'layout' => :'layout',
        :'production_time' => :'productionTime',
        :'envelope' => :'envelope',
        :'color' => :'color',
        :'paper_type' => :'paperType',
        :'print_option' => :'printOption',
        :'mail_class' => :'mailClass'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'document_class' => :'String',
        :'layout' => :'String',
        :'production_time' => :'String',
        :'envelope' => :'String',
        :'color' => :'String',
        :'paper_type' => :'String',
        :'print_option' => :'String',
        :'mail_class' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::JobOptions` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::JobOptions`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'document_class')
        self.document_class = attributes[:'document_class']
      else
        self.document_class = nil
      end

      if attributes.key?(:'layout')
        self.layout = attributes[:'layout']
      else
        self.layout = nil
      end

      if attributes.key?(:'production_time')
        self.production_time = attributes[:'production_time']
      else
        self.production_time = nil
      end

      if attributes.key?(:'envelope')
        self.envelope = attributes[:'envelope']
      else
        self.envelope = nil
      end

      if attributes.key?(:'color')
        self.color = attributes[:'color']
      else
        self.color = nil
      end

      if attributes.key?(:'paper_type')
        self.paper_type = attributes[:'paper_type']
      else
        self.paper_type = nil
      end

      if attributes.key?(:'print_option')
        self.print_option = attributes[:'print_option']
      else
        self.print_option = nil
      end

      if attributes.key?(:'mail_class')
        self.mail_class = attributes[:'mail_class']
      else
        self.mail_class = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @document_class.nil?
        invalid_properties.push('invalid value for "document_class", document_class cannot be nil.')
      end

      if @layout.nil?
        invalid_properties.push('invalid value for "layout", layout cannot be nil.')
      end

      if @production_time.nil?
        invalid_properties.push('invalid value for "production_time", production_time cannot be nil.')
      end

      if @envelope.nil?
        invalid_properties.push('invalid value for "envelope", envelope cannot be nil.')
      end

      if @color.nil?
        invalid_properties.push('invalid value for "color", color cannot be nil.')
      end

      if @paper_type.nil?
        invalid_properties.push('invalid value for "paper_type", paper_type cannot be nil.')
      end

      if @print_option.nil?
        invalid_properties.push('invalid value for "print_option", print_option cannot be nil.')
      end

      if @mail_class.nil?
        invalid_properties.push('invalid value for "mail_class", mail_class cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @document_class.nil?
      return false if @layout.nil?
      return false if @production_time.nil?
      return false if @envelope.nil?
      return false if @color.nil?
      return false if @paper_type.nil?
      return false if @print_option.nil?
      return false if @mail_class.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] document_class Value to be assigned
    def document_class=(document_class)
      if document_class.nil?
        fail ArgumentError, 'document_class cannot be nil'
      end

      @document_class = document_class
    end

    # Custom attribute writer method with validation
    # @param [Object] layout Value to be assigned
    def layout=(layout)
      if layout.nil?
        fail ArgumentError, 'layout cannot be nil'
      end

      @layout = layout
    end

    # Custom attribute writer method with validation
    # @param [Object] production_time Value to be assigned
    def production_time=(production_time)
      if production_time.nil?
        fail ArgumentError, 'production_time cannot be nil'
      end

      @production_time = production_time
    end

    # Custom attribute writer method with validation
    # @param [Object] envelope Value to be assigned
    def envelope=(envelope)
      if envelope.nil?
        fail ArgumentError, 'envelope cannot be nil'
      end

      @envelope = envelope
    end

    # Custom attribute writer method with validation
    # @param [Object] color Value to be assigned
    def color=(color)
      if color.nil?
        fail ArgumentError, 'color cannot be nil'
      end

      @color = color
    end

    # Custom attribute writer method with validation
    # @param [Object] paper_type Value to be assigned
    def paper_type=(paper_type)
      if paper_type.nil?
        fail ArgumentError, 'paper_type cannot be nil'
      end

      @paper_type = paper_type
    end

    # Custom attribute writer method with validation
    # @param [Object] print_option Value to be assigned
    def print_option=(print_option)
      if print_option.nil?
        fail ArgumentError, 'print_option cannot be nil'
      end

      @print_option = print_option
    end

    # Custom attribute writer method with validation
    # @param [Object] mail_class Value to be assigned
    def mail_class=(mail_class)
      if mail_class.nil?
        fail ArgumentError, 'mail_class cannot be nil'
      end

      @mail_class = mail_class
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          document_class == o.document_class &&
          layout == o.layout &&
          production_time == o.production_time &&
          envelope == o.envelope &&
          color == o.color &&
          paper_type == o.paper_type &&
          print_option == o.print_option &&
          mail_class == o.mail_class
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [document_class, layout, production_time, envelope, color, paper_type, print_option, mail_class].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
