/*
C2M API v2

API for submitting mailing jobs with various document routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StandardResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StandardResponse{}

// StandardResponse struct for StandardResponse
type StandardResponse struct {
	Status string `json:"status"`
	Message string `json:"message"`
	RequestId int32 `json:"requestId"`
}

type _StandardResponse StandardResponse

// NewStandardResponse instantiates a new StandardResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStandardResponse(status string, message string, requestId int32) *StandardResponse {
	this := StandardResponse{}
	this.Status = status
	this.Message = message
	this.RequestId = requestId
	return &this
}

// NewStandardResponseWithDefaults instantiates a new StandardResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStandardResponseWithDefaults() *StandardResponse {
	this := StandardResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *StandardResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *StandardResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *StandardResponse) SetStatus(v string) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *StandardResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *StandardResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *StandardResponse) SetMessage(v string) {
	o.Message = v
}

// GetRequestId returns the RequestId field value
func (o *StandardResponse) GetRequestId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *StandardResponse) GetRequestIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *StandardResponse) SetRequestId(v int32) {
	o.RequestId = v
}

func (o StandardResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StandardResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	toSerialize["requestId"] = o.RequestId
	return toSerialize, nil
}

func (o *StandardResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"message",
		"requestId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStandardResponse := _StandardResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStandardResponse)

	if err != nil {
		return err
	}

	*o = StandardResponse(varStandardResponse)

	return err
}

type NullableStandardResponse struct {
	value *StandardResponse
	isSet bool
}

func (v NullableStandardResponse) Get() *StandardResponse {
	return v.value
}

func (v *NullableStandardResponse) Set(val *StandardResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStandardResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStandardResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStandardResponse(val *StandardResponse) *NullableStandardResponse {
	return &NullableStandardResponse{value: val, isSet: true}
}

func (v NullableStandardResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStandardResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


