/*
C2M API v2

API for submitting mailing jobs with various document routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// MergeDocumentRef - struct for MergeDocumentRef
type MergeDocumentRef struct {
	MergeByDocumentId *MergeByDocumentId
	MergeByRequestId *MergeByRequestId
}

// MergeByDocumentIdAsMergeDocumentRef is a convenience function that returns MergeByDocumentId wrapped in MergeDocumentRef
func MergeByDocumentIdAsMergeDocumentRef(v *MergeByDocumentId) MergeDocumentRef {
	return MergeDocumentRef{
		MergeByDocumentId: v,
	}
}

// MergeByRequestIdAsMergeDocumentRef is a convenience function that returns MergeByRequestId wrapped in MergeDocumentRef
func MergeByRequestIdAsMergeDocumentRef(v *MergeByRequestId) MergeDocumentRef {
	return MergeDocumentRef{
		MergeByRequestId: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *MergeDocumentRef) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into MergeByDocumentId
	err = newStrictDecoder(data).Decode(&dst.MergeByDocumentId)
	if err == nil {
		jsonMergeByDocumentId, _ := json.Marshal(dst.MergeByDocumentId)
		if string(jsonMergeByDocumentId) == "{}" { // empty struct
			dst.MergeByDocumentId = nil
		} else {
			if err = validator.Validate(dst.MergeByDocumentId); err != nil {
				dst.MergeByDocumentId = nil
			} else {
				match++
			}
		}
	} else {
		dst.MergeByDocumentId = nil
	}

	// try to unmarshal data into MergeByRequestId
	err = newStrictDecoder(data).Decode(&dst.MergeByRequestId)
	if err == nil {
		jsonMergeByRequestId, _ := json.Marshal(dst.MergeByRequestId)
		if string(jsonMergeByRequestId) == "{}" { // empty struct
			dst.MergeByRequestId = nil
		} else {
			if err = validator.Validate(dst.MergeByRequestId); err != nil {
				dst.MergeByRequestId = nil
			} else {
				match++
			}
		}
	} else {
		dst.MergeByRequestId = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.MergeByDocumentId = nil
		dst.MergeByRequestId = nil

		return fmt.Errorf("data matches more than one schema in oneOf(MergeDocumentRef)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(MergeDocumentRef)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src MergeDocumentRef) MarshalJSON() ([]byte, error) {
	if src.MergeByDocumentId != nil {
		return json.Marshal(&src.MergeByDocumentId)
	}

	if src.MergeByRequestId != nil {
		return json.Marshal(&src.MergeByRequestId)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *MergeDocumentRef) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.MergeByDocumentId != nil {
		return obj.MergeByDocumentId
	}

	if obj.MergeByRequestId != nil {
		return obj.MergeByRequestId
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj MergeDocumentRef) GetActualInstanceValue() (interface{}) {
	if obj.MergeByDocumentId != nil {
		return *obj.MergeByDocumentId
	}

	if obj.MergeByRequestId != nil {
		return *obj.MergeByRequestId
	}

	// all schemas are nil
	return nil
}

type NullableMergeDocumentRef struct {
	value *MergeDocumentRef
	isSet bool
}

func (v NullableMergeDocumentRef) Get() *MergeDocumentRef {
	return v.value
}

func (v *NullableMergeDocumentRef) Set(val *MergeDocumentRef) {
	v.value = val
	v.isSet = true
}

func (v NullableMergeDocumentRef) IsSet() bool {
	return v.isSet
}

func (v *NullableMergeDocumentRef) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMergeDocumentRef(val *MergeDocumentRef) *NullableMergeDocumentRef {
	return &NullableMergeDocumentRef{value: val, isSet: true}
}

func (v NullableMergeDocumentRef) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMergeDocumentRef) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


