/*
C2M API v2

API for submitting mailing jobs with various document routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// RecipientAddressSource - struct for RecipientAddressSource
type RecipientAddressSource struct {
	RecipientAddressSourceOneOf *RecipientAddressSourceOneOf
	RecipientAddressSourceOneOf1 *RecipientAddressSourceOneOf1
	RecipientAddressSourceOneOf2 *RecipientAddressSourceOneOf2
	RecipientAddressSourceOneOf3 *RecipientAddressSourceOneOf3
}

// RecipientAddressSourceOneOfAsRecipientAddressSource is a convenience function that returns RecipientAddressSourceOneOf wrapped in RecipientAddressSource
func RecipientAddressSourceOneOfAsRecipientAddressSource(v *RecipientAddressSourceOneOf) RecipientAddressSource {
	return RecipientAddressSource{
		RecipientAddressSourceOneOf: v,
	}
}

// RecipientAddressSourceOneOf1AsRecipientAddressSource is a convenience function that returns RecipientAddressSourceOneOf1 wrapped in RecipientAddressSource
func RecipientAddressSourceOneOf1AsRecipientAddressSource(v *RecipientAddressSourceOneOf1) RecipientAddressSource {
	return RecipientAddressSource{
		RecipientAddressSourceOneOf1: v,
	}
}

// RecipientAddressSourceOneOf2AsRecipientAddressSource is a convenience function that returns RecipientAddressSourceOneOf2 wrapped in RecipientAddressSource
func RecipientAddressSourceOneOf2AsRecipientAddressSource(v *RecipientAddressSourceOneOf2) RecipientAddressSource {
	return RecipientAddressSource{
		RecipientAddressSourceOneOf2: v,
	}
}

// RecipientAddressSourceOneOf3AsRecipientAddressSource is a convenience function that returns RecipientAddressSourceOneOf3 wrapped in RecipientAddressSource
func RecipientAddressSourceOneOf3AsRecipientAddressSource(v *RecipientAddressSourceOneOf3) RecipientAddressSource {
	return RecipientAddressSource{
		RecipientAddressSourceOneOf3: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *RecipientAddressSource) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into RecipientAddressSourceOneOf
	err = newStrictDecoder(data).Decode(&dst.RecipientAddressSourceOneOf)
	if err == nil {
		jsonRecipientAddressSourceOneOf, _ := json.Marshal(dst.RecipientAddressSourceOneOf)
		if string(jsonRecipientAddressSourceOneOf) == "{}" { // empty struct
			dst.RecipientAddressSourceOneOf = nil
		} else {
			if err = validator.Validate(dst.RecipientAddressSourceOneOf); err != nil {
				dst.RecipientAddressSourceOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.RecipientAddressSourceOneOf = nil
	}

	// try to unmarshal data into RecipientAddressSourceOneOf1
	err = newStrictDecoder(data).Decode(&dst.RecipientAddressSourceOneOf1)
	if err == nil {
		jsonRecipientAddressSourceOneOf1, _ := json.Marshal(dst.RecipientAddressSourceOneOf1)
		if string(jsonRecipientAddressSourceOneOf1) == "{}" { // empty struct
			dst.RecipientAddressSourceOneOf1 = nil
		} else {
			if err = validator.Validate(dst.RecipientAddressSourceOneOf1); err != nil {
				dst.RecipientAddressSourceOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.RecipientAddressSourceOneOf1 = nil
	}

	// try to unmarshal data into RecipientAddressSourceOneOf2
	err = newStrictDecoder(data).Decode(&dst.RecipientAddressSourceOneOf2)
	if err == nil {
		jsonRecipientAddressSourceOneOf2, _ := json.Marshal(dst.RecipientAddressSourceOneOf2)
		if string(jsonRecipientAddressSourceOneOf2) == "{}" { // empty struct
			dst.RecipientAddressSourceOneOf2 = nil
		} else {
			if err = validator.Validate(dst.RecipientAddressSourceOneOf2); err != nil {
				dst.RecipientAddressSourceOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.RecipientAddressSourceOneOf2 = nil
	}

	// try to unmarshal data into RecipientAddressSourceOneOf3
	err = newStrictDecoder(data).Decode(&dst.RecipientAddressSourceOneOf3)
	if err == nil {
		jsonRecipientAddressSourceOneOf3, _ := json.Marshal(dst.RecipientAddressSourceOneOf3)
		if string(jsonRecipientAddressSourceOneOf3) == "{}" { // empty struct
			dst.RecipientAddressSourceOneOf3 = nil
		} else {
			if err = validator.Validate(dst.RecipientAddressSourceOneOf3); err != nil {
				dst.RecipientAddressSourceOneOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.RecipientAddressSourceOneOf3 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.RecipientAddressSourceOneOf = nil
		dst.RecipientAddressSourceOneOf1 = nil
		dst.RecipientAddressSourceOneOf2 = nil
		dst.RecipientAddressSourceOneOf3 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(RecipientAddressSource)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(RecipientAddressSource)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src RecipientAddressSource) MarshalJSON() ([]byte, error) {
	if src.RecipientAddressSourceOneOf != nil {
		return json.Marshal(&src.RecipientAddressSourceOneOf)
	}

	if src.RecipientAddressSourceOneOf1 != nil {
		return json.Marshal(&src.RecipientAddressSourceOneOf1)
	}

	if src.RecipientAddressSourceOneOf2 != nil {
		return json.Marshal(&src.RecipientAddressSourceOneOf2)
	}

	if src.RecipientAddressSourceOneOf3 != nil {
		return json.Marshal(&src.RecipientAddressSourceOneOf3)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *RecipientAddressSource) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.RecipientAddressSourceOneOf != nil {
		return obj.RecipientAddressSourceOneOf
	}

	if obj.RecipientAddressSourceOneOf1 != nil {
		return obj.RecipientAddressSourceOneOf1
	}

	if obj.RecipientAddressSourceOneOf2 != nil {
		return obj.RecipientAddressSourceOneOf2
	}

	if obj.RecipientAddressSourceOneOf3 != nil {
		return obj.RecipientAddressSourceOneOf3
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj RecipientAddressSource) GetActualInstanceValue() (interface{}) {
	if obj.RecipientAddressSourceOneOf != nil {
		return *obj.RecipientAddressSourceOneOf
	}

	if obj.RecipientAddressSourceOneOf1 != nil {
		return *obj.RecipientAddressSourceOneOf1
	}

	if obj.RecipientAddressSourceOneOf2 != nil {
		return *obj.RecipientAddressSourceOneOf2
	}

	if obj.RecipientAddressSourceOneOf3 != nil {
		return *obj.RecipientAddressSourceOneOf3
	}

	// all schemas are nil
	return nil
}

type NullableRecipientAddressSource struct {
	value *RecipientAddressSource
	isSet bool
}

func (v NullableRecipientAddressSource) Get() *RecipientAddressSource {
	return v.value
}

func (v *NullableRecipientAddressSource) Set(val *RecipientAddressSource) {
	v.value = val
	v.isSet = true
}

func (v NullableRecipientAddressSource) IsSet() bool {
	return v.isSet
}

func (v *NullableRecipientAddressSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecipientAddressSource(val *RecipientAddressSource) *NullableRecipientAddressSource {
	return &NullableRecipientAddressSource{value: val, isSet: true}
}

func (v NullableRecipientAddressSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecipientAddressSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


