/*
C2M API v2

API for submitting mailing jobs with various document routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DocSourceZipFileRefOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocSourceZipFileRefOneOf{}

// DocSourceZipFileRefOneOf struct for DocSourceZipFileRefOneOf
type DocSourceZipFileRefOneOf struct {
	ZipDocumentIdOnly ZipDocumentIdOnly `json:"zipDocumentIdOnly"`
}

type _DocSourceZipFileRefOneOf DocSourceZipFileRefOneOf

// NewDocSourceZipFileRefOneOf instantiates a new DocSourceZipFileRefOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocSourceZipFileRefOneOf(zipDocumentIdOnly ZipDocumentIdOnly) *DocSourceZipFileRefOneOf {
	this := DocSourceZipFileRefOneOf{}
	this.ZipDocumentIdOnly = zipDocumentIdOnly
	return &this
}

// NewDocSourceZipFileRefOneOfWithDefaults instantiates a new DocSourceZipFileRefOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocSourceZipFileRefOneOfWithDefaults() *DocSourceZipFileRefOneOf {
	this := DocSourceZipFileRefOneOf{}
	return &this
}

// GetZipDocumentIdOnly returns the ZipDocumentIdOnly field value
func (o *DocSourceZipFileRefOneOf) GetZipDocumentIdOnly() ZipDocumentIdOnly {
	if o == nil {
		var ret ZipDocumentIdOnly
		return ret
	}

	return o.ZipDocumentIdOnly
}

// GetZipDocumentIdOnlyOk returns a tuple with the ZipDocumentIdOnly field value
// and a boolean to check if the value has been set.
func (o *DocSourceZipFileRefOneOf) GetZipDocumentIdOnlyOk() (*ZipDocumentIdOnly, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZipDocumentIdOnly, true
}

// SetZipDocumentIdOnly sets field value
func (o *DocSourceZipFileRefOneOf) SetZipDocumentIdOnly(v ZipDocumentIdOnly) {
	o.ZipDocumentIdOnly = v
}

func (o DocSourceZipFileRefOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocSourceZipFileRefOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["zipDocumentIdOnly"] = o.ZipDocumentIdOnly
	return toSerialize, nil
}

func (o *DocSourceZipFileRefOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"zipDocumentIdOnly",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDocSourceZipFileRefOneOf := _DocSourceZipFileRefOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDocSourceZipFileRefOneOf)

	if err != nil {
		return err
	}

	*o = DocSourceZipFileRefOneOf(varDocSourceZipFileRefOneOf)

	return err
}

type NullableDocSourceZipFileRefOneOf struct {
	value *DocSourceZipFileRefOneOf
	isSet bool
}

func (v NullableDocSourceZipFileRefOneOf) Get() *DocSourceZipFileRefOneOf {
	return v.value
}

func (v *NullableDocSourceZipFileRefOneOf) Set(val *DocSourceZipFileRefOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableDocSourceZipFileRefOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableDocSourceZipFileRefOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocSourceZipFileRefOneOf(val *DocSourceZipFileRefOneOf) *NullableDocSourceZipFileRefOneOf {
	return &NullableDocSourceZipFileRefOneOf{value: val, isSet: true}
}

func (v NullableDocSourceZipFileRefOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocSourceZipFileRefOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


