/*
C2M API v2 - Auth Overlay

API for submitting documents with various routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// DocSourceZipFile - struct for DocSourceZipFile
type DocSourceZipFile struct {
	ZipDocumentIdSource *ZipDocumentIdSource
	ZipRequestIdSource *ZipRequestIdSource
}

// ZipDocumentIdSourceAsDocSourceZipFile is a convenience function that returns ZipDocumentIdSource wrapped in DocSourceZipFile
func ZipDocumentIdSourceAsDocSourceZipFile(v *ZipDocumentIdSource) DocSourceZipFile {
	return DocSourceZipFile{
		ZipDocumentIdSource: v,
	}
}

// ZipRequestIdSourceAsDocSourceZipFile is a convenience function that returns ZipRequestIdSource wrapped in DocSourceZipFile
func ZipRequestIdSourceAsDocSourceZipFile(v *ZipRequestIdSource) DocSourceZipFile {
	return DocSourceZipFile{
		ZipRequestIdSource: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *DocSourceZipFile) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ZipDocumentIdSource
	err = newStrictDecoder(data).Decode(&dst.ZipDocumentIdSource)
	if err == nil {
		jsonZipDocumentIdSource, _ := json.Marshal(dst.ZipDocumentIdSource)
		if string(jsonZipDocumentIdSource) == "{}" { // empty struct
			dst.ZipDocumentIdSource = nil
		} else {
			if err = validator.Validate(dst.ZipDocumentIdSource); err != nil {
				dst.ZipDocumentIdSource = nil
			} else {
				match++
			}
		}
	} else {
		dst.ZipDocumentIdSource = nil
	}

	// try to unmarshal data into ZipRequestIdSource
	err = newStrictDecoder(data).Decode(&dst.ZipRequestIdSource)
	if err == nil {
		jsonZipRequestIdSource, _ := json.Marshal(dst.ZipRequestIdSource)
		if string(jsonZipRequestIdSource) == "{}" { // empty struct
			dst.ZipRequestIdSource = nil
		} else {
			if err = validator.Validate(dst.ZipRequestIdSource); err != nil {
				dst.ZipRequestIdSource = nil
			} else {
				match++
			}
		}
	} else {
		dst.ZipRequestIdSource = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ZipDocumentIdSource = nil
		dst.ZipRequestIdSource = nil

		return fmt.Errorf("data matches more than one schema in oneOf(DocSourceZipFile)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(DocSourceZipFile)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DocSourceZipFile) MarshalJSON() ([]byte, error) {
	if src.ZipDocumentIdSource != nil {
		return json.Marshal(&src.ZipDocumentIdSource)
	}

	if src.ZipRequestIdSource != nil {
		return json.Marshal(&src.ZipRequestIdSource)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *DocSourceZipFile) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ZipDocumentIdSource != nil {
		return obj.ZipDocumentIdSource
	}

	if obj.ZipRequestIdSource != nil {
		return obj.ZipRequestIdSource
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj DocSourceZipFile) GetActualInstanceValue() (interface{}) {
	if obj.ZipDocumentIdSource != nil {
		return *obj.ZipDocumentIdSource
	}

	if obj.ZipRequestIdSource != nil {
		return *obj.ZipRequestIdSource
	}

	// all schemas are nil
	return nil
}

type NullableDocSourceZipFile struct {
	value *DocSourceZipFile
	isSet bool
}

func (v NullableDocSourceZipFile) Get() *DocSourceZipFile {
	return v.value
}

func (v *NullableDocSourceZipFile) Set(val *DocSourceZipFile) {
	v.value = val
	v.isSet = true
}

func (v NullableDocSourceZipFile) IsSet() bool {
	return v.isSet
}

func (v *NullableDocSourceZipFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocSourceZipFile(val *DocSourceZipFile) *NullableDocSourceZipFile {
	return &NullableDocSourceZipFile{value: val, isSet: true}
}

func (v NullableDocSourceZipFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocSourceZipFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


