/*
C2M API v2 - Auth Overlay

API for submitting documents with various routing options

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package c2mapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// DocumentSource - struct for DocumentSource
type DocumentSource struct {
	RequestIdSource *RequestIdSource
	ZipDocumentIdSource *ZipDocumentIdSource
	ZipRequestIdSource *ZipRequestIdSource
	Int32 *int32
	String *string
}

// RequestIdSourceAsDocumentSource is a convenience function that returns RequestIdSource wrapped in DocumentSource
func RequestIdSourceAsDocumentSource(v *RequestIdSource) DocumentSource {
	return DocumentSource{
		RequestIdSource: v,
	}
}

// ZipDocumentIdSourceAsDocumentSource is a convenience function that returns ZipDocumentIdSource wrapped in DocumentSource
func ZipDocumentIdSourceAsDocumentSource(v *ZipDocumentIdSource) DocumentSource {
	return DocumentSource{
		ZipDocumentIdSource: v,
	}
}

// ZipRequestIdSourceAsDocumentSource is a convenience function that returns ZipRequestIdSource wrapped in DocumentSource
func ZipRequestIdSourceAsDocumentSource(v *ZipRequestIdSource) DocumentSource {
	return DocumentSource{
		ZipRequestIdSource: v,
	}
}

// int32AsDocumentSource is a convenience function that returns int32 wrapped in DocumentSource
func Int32AsDocumentSource(v *int32) DocumentSource {
	return DocumentSource{
		Int32: v,
	}
}

// stringAsDocumentSource is a convenience function that returns string wrapped in DocumentSource
func StringAsDocumentSource(v *string) DocumentSource {
	return DocumentSource{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *DocumentSource) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into RequestIdSource
	err = newStrictDecoder(data).Decode(&dst.RequestIdSource)
	if err == nil {
		jsonRequestIdSource, _ := json.Marshal(dst.RequestIdSource)
		if string(jsonRequestIdSource) == "{}" { // empty struct
			dst.RequestIdSource = nil
		} else {
			if err = validator.Validate(dst.RequestIdSource); err != nil {
				dst.RequestIdSource = nil
			} else {
				match++
			}
		}
	} else {
		dst.RequestIdSource = nil
	}

	// try to unmarshal data into ZipDocumentIdSource
	err = newStrictDecoder(data).Decode(&dst.ZipDocumentIdSource)
	if err == nil {
		jsonZipDocumentIdSource, _ := json.Marshal(dst.ZipDocumentIdSource)
		if string(jsonZipDocumentIdSource) == "{}" { // empty struct
			dst.ZipDocumentIdSource = nil
		} else {
			if err = validator.Validate(dst.ZipDocumentIdSource); err != nil {
				dst.ZipDocumentIdSource = nil
			} else {
				match++
			}
		}
	} else {
		dst.ZipDocumentIdSource = nil
	}

	// try to unmarshal data into ZipRequestIdSource
	err = newStrictDecoder(data).Decode(&dst.ZipRequestIdSource)
	if err == nil {
		jsonZipRequestIdSource, _ := json.Marshal(dst.ZipRequestIdSource)
		if string(jsonZipRequestIdSource) == "{}" { // empty struct
			dst.ZipRequestIdSource = nil
		} else {
			if err = validator.Validate(dst.ZipRequestIdSource); err != nil {
				dst.ZipRequestIdSource = nil
			} else {
				match++
			}
		}
	} else {
		dst.ZipRequestIdSource = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.RequestIdSource = nil
		dst.ZipDocumentIdSource = nil
		dst.ZipRequestIdSource = nil
		dst.Int32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(DocumentSource)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(DocumentSource)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src DocumentSource) MarshalJSON() ([]byte, error) {
	if src.RequestIdSource != nil {
		return json.Marshal(&src.RequestIdSource)
	}

	if src.ZipDocumentIdSource != nil {
		return json.Marshal(&src.ZipDocumentIdSource)
	}

	if src.ZipRequestIdSource != nil {
		return json.Marshal(&src.ZipRequestIdSource)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *DocumentSource) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.RequestIdSource != nil {
		return obj.RequestIdSource
	}

	if obj.ZipDocumentIdSource != nil {
		return obj.ZipDocumentIdSource
	}

	if obj.ZipRequestIdSource != nil {
		return obj.ZipRequestIdSource
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj DocumentSource) GetActualInstanceValue() (interface{}) {
	if obj.RequestIdSource != nil {
		return *obj.RequestIdSource
	}

	if obj.ZipDocumentIdSource != nil {
		return *obj.ZipDocumentIdSource
	}

	if obj.ZipRequestIdSource != nil {
		return *obj.ZipRequestIdSource
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableDocumentSource struct {
	value *DocumentSource
	isSet bool
}

func (v NullableDocumentSource) Get() *DocumentSource {
	return v.value
}

func (v *NullableDocumentSource) Set(val *DocumentSource) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentSource) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentSource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentSource(val *DocumentSource) *NullableDocumentSource {
	return &NullableDocumentSource{value: val, isSet: true}
}

func (v NullableDocumentSource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentSource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


