/**
 * C2M API v2 - Auth Overlay
 * API for submitting documents with various routing options
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/c2m_api/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/c2m_api/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.C2MApiV2AuthOverlay);
  }
}(this, function(expect, C2MApiV2AuthOverlay) {
  'use strict';

  var instance;

  beforeEach(function() {
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ErrorCode', function() {
    it('should create an instance of ErrorCode', function() {
      // uncomment below and update the code to test ErrorCode
      //var instance = new C2MApiV2AuthOverlay.ErrorCode();
      //expect(instance).to.be.a(C2MApiV2AuthOverlay.ErrorCode);
    });

  });

}));
