//
// JobsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class JobsAPI {

    /**
     Submit a multi zip addressCapture job
     
     - parameter submitMultiZipAddressCaptureParams: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func submitMultiZipAddressCaptureParams(submitMultiZipAddressCaptureParams: SubmitMultiZipAddressCaptureParams, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: StandardResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return submitMultiZipAddressCaptureParamsWithRequestBuilder(submitMultiZipAddressCaptureParams: submitMultiZipAddressCaptureParams).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Submit a multi zip addressCapture job
     - POST /jobs/submit/multi/zip/addressCapture
     - Submits a multi zip addressCapture mailing job. The request body contains job parameters including document source, recipient address information, and payment details.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter submitMultiZipAddressCaptureParams: (body)  
     - returns: RequestBuilder<StandardResponse> 
     */
    open class func submitMultiZipAddressCaptureParamsWithRequestBuilder(submitMultiZipAddressCaptureParams: SubmitMultiZipAddressCaptureParams) -> RequestBuilder<StandardResponse> {
        let localVariablePath = "/jobs/submit/multi/zip/addressCapture"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: submitMultiZipAddressCaptureParams)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StandardResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Submit a multi zip job
     
     - parameter submitMultiZipParams: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func submitMultiZipParams(submitMultiZipParams: SubmitMultiZipParams, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: StandardResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return submitMultiZipParamsWithRequestBuilder(submitMultiZipParams: submitMultiZipParams).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Submit a multi zip job
     - POST /jobs/submit/multi/zip
     - Submits a multi zip mailing job. The request body contains job parameters including document source, recipient address information, and payment details.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter submitMultiZipParams: (body)  
     - returns: RequestBuilder<StandardResponse> 
     */
    open class func submitMultiZipParamsWithRequestBuilder(submitMultiZipParams: SubmitMultiZipParams) -> RequestBuilder<StandardResponse> {
        let localVariablePath = "/jobs/submit/multi/zip"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: submitMultiZipParams)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StandardResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Submit a single pdf addressCapture job
     
     - parameter submitSinglePdfAddressCaptureParams: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func submitSinglePdfAddressCaptureParams(submitSinglePdfAddressCaptureParams: SubmitSinglePdfAddressCaptureParams, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: StandardResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return submitSinglePdfAddressCaptureParamsWithRequestBuilder(submitSinglePdfAddressCaptureParams: submitSinglePdfAddressCaptureParams).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Submit a single pdf addressCapture job
     - POST /jobs/submit/single/pdf/addressCapture
     - Submits a single pdf addressCapture mailing job. The request body contains job parameters including document source, recipient address information, and payment details.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter submitSinglePdfAddressCaptureParams: (body)  
     - returns: RequestBuilder<StandardResponse> 
     */
    open class func submitSinglePdfAddressCaptureParamsWithRequestBuilder(submitSinglePdfAddressCaptureParams: SubmitSinglePdfAddressCaptureParams) -> RequestBuilder<StandardResponse> {
        let localVariablePath = "/jobs/submit/single/pdf/addressCapture"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: submitSinglePdfAddressCaptureParams)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StandardResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Submit a single pdf split addressCapture job
     
     - parameter submitSinglePdfSplitAddressCaptureParams: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func submitSinglePdfSplitAddressCaptureParams(submitSinglePdfSplitAddressCaptureParams: SubmitSinglePdfSplitAddressCaptureParams, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: StandardResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return submitSinglePdfSplitAddressCaptureParamsWithRequestBuilder(submitSinglePdfSplitAddressCaptureParams: submitSinglePdfSplitAddressCaptureParams).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Submit a single pdf split addressCapture job
     - POST /jobs/submit/single/pdf/split/addressCapture
     - Submits a single pdf split addressCapture mailing job. The request body contains job parameters including document source, recipient address information, and payment details.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter submitSinglePdfSplitAddressCaptureParams: (body)  
     - returns: RequestBuilder<StandardResponse> 
     */
    open class func submitSinglePdfSplitAddressCaptureParamsWithRequestBuilder(submitSinglePdfSplitAddressCaptureParams: SubmitSinglePdfSplitAddressCaptureParams) -> RequestBuilder<StandardResponse> {
        let localVariablePath = "/jobs/submit/single/pdf/split/addressCapture"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: submitSinglePdfSplitAddressCaptureParams)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StandardResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Submit a single pdf split job
     
     - parameter submitSinglePdfSplitParams: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func submitSinglePdfSplitParams(submitSinglePdfSplitParams: SubmitSinglePdfSplitParams, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: StandardResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return submitSinglePdfSplitParamsWithRequestBuilder(submitSinglePdfSplitParams: submitSinglePdfSplitParams).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Submit a single pdf split job
     - POST /jobs/submit/single/pdf/split
     - Submits a single pdf split mailing job. The request body contains job parameters including document source, recipient address information, and payment details.
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter submitSinglePdfSplitParams: (body)  
     - returns: RequestBuilder<StandardResponse> 
     */
    open class func submitSinglePdfSplitParamsWithRequestBuilder(submitSinglePdfSplitParams: SubmitSinglePdfSplitParams) -> RequestBuilder<StandardResponse> {
        let localVariablePath = "/jobs/submit/single/pdf/split"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: submitSinglePdfSplitParams)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StandardResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
