//
// JobsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class JobsAPI {

    /**
     Submitmultidocmergeparams
     
     - parameter submitMultiDocMergeParams: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func submitMultiDocMergeParams(submitMultiDocMergeParams: SubmitMultiDocMergeParams, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: StandardResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return submitMultiDocMergeParamsWithRequestBuilder(submitMultiDocMergeParams: submitMultiDocMergeParams).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Submitmultidocmergeparams
     - POST /mail-merge
     - API endpoint for submitMultiDocMergeParams
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter submitMultiDocMergeParams: (body)  
     - returns: RequestBuilder<StandardResponse> 
     */
    open class func submitMultiDocMergeParamsWithRequestBuilder(submitMultiDocMergeParams: SubmitMultiDocMergeParams) -> RequestBuilder<StandardResponse> {
        let localVariablePath = "/mail-merge"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: submitMultiDocMergeParams)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StandardResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Submitmultidocparams
     
     - parameter submitMultiDocParams: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func submitMultiDocParams(submitMultiDocParams: SubmitMultiDocParams, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: StandardResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return submitMultiDocParamsWithRequestBuilder(submitMultiDocParams: submitMultiDocParams).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Submitmultidocparams
     - POST /static/multi
     - API endpoint for submitMultiDocParams
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter submitMultiDocParams: (body)  
     - returns: RequestBuilder<StandardResponse> 
     */
    open class func submitMultiDocParamsWithRequestBuilder(submitMultiDocParams: SubmitMultiDocParams) -> RequestBuilder<StandardResponse> {
        let localVariablePath = "/static/multi"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: submitMultiDocParams)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StandardResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Submitmultizipaddresscaptureparams
     
     - parameter submitMultiZipAddressCaptureParams: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func submitMultiZipAddressCaptureParams(submitMultiZipAddressCaptureParams: SubmitMultiZipAddressCaptureParams, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: StandardResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return submitMultiZipAddressCaptureParamsWithRequestBuilder(submitMultiZipAddressCaptureParams: submitMultiZipAddressCaptureParams).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Submitmultizipaddresscaptureparams
     - POST /batch/zip/address-capture
     - API endpoint for submitMultiZipAddressCaptureParams
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter submitMultiZipAddressCaptureParams: (body)  
     - returns: RequestBuilder<StandardResponse> 
     */
    open class func submitMultiZipAddressCaptureParamsWithRequestBuilder(submitMultiZipAddressCaptureParams: SubmitMultiZipAddressCaptureParams) -> RequestBuilder<StandardResponse> {
        let localVariablePath = "/batch/zip/address-capture"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: submitMultiZipAddressCaptureParams)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StandardResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Submitmultizipparams
     
     - parameter submitMultiZipParams: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func submitMultiZipParams(submitMultiZipParams: SubmitMultiZipParams, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: StandardResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return submitMultiZipParamsWithRequestBuilder(submitMultiZipParams: submitMultiZipParams).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Submitmultizipparams
     - POST /batch/zip
     - API endpoint for submitMultiZipParams
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter submitMultiZipParams: (body)  
     - returns: RequestBuilder<StandardResponse> 
     */
    open class func submitMultiZipParamsWithRequestBuilder(submitMultiZipParams: SubmitMultiZipParams) -> RequestBuilder<StandardResponse> {
        let localVariablePath = "/batch/zip"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: submitMultiZipParams)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StandardResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Submitsingledocparams
     
     - parameter submitSingleDocParams: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func submitSingleDocParams(submitSingleDocParams: SubmitSingleDocParams, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: StandardResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return submitSingleDocParamsWithRequestBuilder(submitSingleDocParams: submitSingleDocParams).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Submitsingledocparams
     - POST /static
     - API endpoint for submitSingleDocParams
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter submitSingleDocParams: (body)  
     - returns: RequestBuilder<StandardResponse> 
     */
    open class func submitSingleDocParamsWithRequestBuilder(submitSingleDocParams: SubmitSingleDocParams) -> RequestBuilder<StandardResponse> {
        let localVariablePath = "/static"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: submitSingleDocParams)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StandardResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Submitsinglepdfaddresscaptureparams
     
     - parameter submitSinglePdfAddressCaptureParams: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func submitSinglePdfAddressCaptureParams(submitSinglePdfAddressCaptureParams: SubmitSinglePdfAddressCaptureParams, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: StandardResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return submitSinglePdfAddressCaptureParamsWithRequestBuilder(submitSinglePdfAddressCaptureParams: submitSinglePdfAddressCaptureParams).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Submitsinglepdfaddresscaptureparams
     - POST /static/address-capture
     - API endpoint for submitSinglePdfAddressCaptureParams
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter submitSinglePdfAddressCaptureParams: (body)  
     - returns: RequestBuilder<StandardResponse> 
     */
    open class func submitSinglePdfAddressCaptureParamsWithRequestBuilder(submitSinglePdfAddressCaptureParams: SubmitSinglePdfAddressCaptureParams) -> RequestBuilder<StandardResponse> {
        let localVariablePath = "/static/address-capture"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: submitSinglePdfAddressCaptureParams)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StandardResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Submitsinglepdfsplitaddresscaptureparams
     
     - parameter submitSinglePdfSplitAddressCaptureParams: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func submitSinglePdfSplitAddressCaptureParams(submitSinglePdfSplitAddressCaptureParams: SubmitSinglePdfSplitAddressCaptureParams, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: StandardResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return submitSinglePdfSplitAddressCaptureParamsWithRequestBuilder(submitSinglePdfSplitAddressCaptureParams: submitSinglePdfSplitAddressCaptureParams).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Submitsinglepdfsplitaddresscaptureparams
     - POST /batch/split/address-capture
     - API endpoint for submitSinglePdfSplitAddressCaptureParams
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter submitSinglePdfSplitAddressCaptureParams: (body)  
     - returns: RequestBuilder<StandardResponse> 
     */
    open class func submitSinglePdfSplitAddressCaptureParamsWithRequestBuilder(submitSinglePdfSplitAddressCaptureParams: SubmitSinglePdfSplitAddressCaptureParams) -> RequestBuilder<StandardResponse> {
        let localVariablePath = "/batch/split/address-capture"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: submitSinglePdfSplitAddressCaptureParams)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StandardResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**
     Submitsinglepdfsplitparams
     
     - parameter submitSinglePdfSplitParams: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func submitSinglePdfSplitParams(submitSinglePdfSplitParams: SubmitSinglePdfSplitParams, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: StandardResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return submitSinglePdfSplitParamsWithRequestBuilder(submitSinglePdfSplitParams: submitSinglePdfSplitParams).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Submitsinglepdfsplitparams
     - POST /batch/split
     - API endpoint for submitSinglePdfSplitParams
     - Bearer Token:
       - type: http
       - name: bearerAuth
     - parameter submitSinglePdfSplitParams: (body)  
     - returns: RequestBuilder<StandardResponse> 
     */
    open class func submitSinglePdfSplitParamsWithRequestBuilder(submitSinglePdfSplitParams: SubmitSinglePdfSplitParams) -> RequestBuilder<StandardResponse> {
        let localVariablePath = "/batch/split"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: submitSinglePdfSplitParams)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<StandardResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
